/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// UEContextInSMSFDataRetrievalAPIService is a service that implements the logic for the UEContextInSMSFDataRetrievalAPIServicer
// This service should implement the business logic for every endpoint for the UEContextInSMSFDataRetrievalAPI API.
// Include any external packages or services that will be required by this service.
type UEContextInSMSFDataRetrievalAPIService struct {
}

// NewUEContextInSMSFDataRetrievalAPIService creates a default api service
func NewUEContextInSMSFDataRetrievalAPIService() UEContextInSMSFDataRetrievalAPIServicer {
	return &UEContextInSMSFDataRetrievalAPIService{}
}

// GetUeCtxInSmsfData - retrieve a UE&#39;s UE Context In SMSF Data
func (s *UEContextInSMSFDataRetrievalAPIService) GetUeCtxInSmsfData(ctx context.Context, supi string, supportedFeatures string) (ImplResponse, error) {
	// TODO - update GetUeCtxInSmsfData with the required logic for this service method.
	// Add api_ue_context_in_smsf_data_retrieval_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UeContextInSmsfData{}) or use other options such as http.Ok ...
	// return Response(200, UeContextInSmsfData{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(500, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(503, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUeCtxInSmsfData method not implemented")
}
