/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// LCSPrivacyDataRetrievalAPIService is a service that implements the logic for the LCSPrivacyDataRetrievalAPIServicer
// This service should implement the business logic for every endpoint for the LCSPrivacyDataRetrievalAPI API.
// Include any external packages or services that will be required by this service.
type LCSPrivacyDataRetrievalAPIService struct {
}

// NewLCSPrivacyDataRetrievalAPIService creates a default api service
func NewLCSPrivacyDataRetrievalAPIService() LCSPrivacyDataRetrievalAPIServicer {
	return &LCSPrivacyDataRetrievalAPIService{}
}

// GetLcsPrivacyData - retrieve a UE&#39;s LCS Privacy Subscription Data
func (s *LCSPrivacyDataRetrievalAPIService) GetLcsPrivacyData(ctx context.Context, ueId string, supportedFeatures string, ifNoneMatch string, ifModifiedSince string) (ImplResponse, error) {
	// TODO - update GetLcsPrivacyData with the required logic for this service method.
	// Add api_lcs_privacy_data_retrieval_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LcsPrivacyData{}) or use other options such as http.Ok ...
	// return Response(200, LcsPrivacyData{}), nil

	// TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(400, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(500, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(503, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLcsPrivacyData method not implemented")
}
