/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	//	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// EnhancedCoverageRestrictionDataRetrievalAPIController binds http requests to an api service and writes the service results to the http response
type EnhancedCoverageRestrictionDataRetrievalAPIController struct {
	service      EnhancedCoverageRestrictionDataRetrievalAPIServicer
	errorHandler ErrorHandler
}

// EnhancedCoverageRestrictionDataRetrievalAPIOption for how the controller is set up.
type EnhancedCoverageRestrictionDataRetrievalAPIOption func(*EnhancedCoverageRestrictionDataRetrievalAPIController)

// WithEnhancedCoverageRestrictionDataRetrievalAPIErrorHandler inject ErrorHandler into controller
func WithEnhancedCoverageRestrictionDataRetrievalAPIErrorHandler(h ErrorHandler) EnhancedCoverageRestrictionDataRetrievalAPIOption {
	return func(c *EnhancedCoverageRestrictionDataRetrievalAPIController) {
		c.errorHandler = h
	}
}

// NewEnhancedCoverageRestrictionDataRetrievalAPIController creates a default api controller
func NewEnhancedCoverageRestrictionDataRetrievalAPIController(s EnhancedCoverageRestrictionDataRetrievalAPIServicer, opts ...EnhancedCoverageRestrictionDataRetrievalAPIOption) Router {
	controller := &EnhancedCoverageRestrictionDataRetrievalAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the EnhancedCoverageRestrictionDataRetrievalAPIController
func (c *EnhancedCoverageRestrictionDataRetrievalAPIController) Routes() Routes {
	return Routes{
		"GetEcrData": Route{
			strings.ToUpper("Get"),
			"/nudm-sdm/v2/{supi}/am-data/ecr-data",
			c.GetEcrData,
		},
	}
}

// GetEcrData - retrieve a UE's subscribed Enhanced Coverage Restriction Data
func (c *EnhancedCoverageRestrictionDataRetrievalAPIController) GetEcrData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	supiParam := params["supi"]
	if supiParam == "" {
		c.errorHandler(w, r, &RequiredError{"supi"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.GetEcrData(r.Context(), supiParam, supportedFeaturesParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
