/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// UserConsentSubscriptionDataRetrievalAPIController binds http requests to an api service and writes the service results to the http response
type UserConsentSubscriptionDataRetrievalAPIController struct {
	service      UserConsentSubscriptionDataRetrievalAPIServicer
	errorHandler ErrorHandler
}

// UserConsentSubscriptionDataRetrievalAPIOption for how the controller is set up.
type UserConsentSubscriptionDataRetrievalAPIOption func(*UserConsentSubscriptionDataRetrievalAPIController)

// WithUserConsentSubscriptionDataRetrievalAPIErrorHandler inject ErrorHandler into controller
func WithUserConsentSubscriptionDataRetrievalAPIErrorHandler(h ErrorHandler) UserConsentSubscriptionDataRetrievalAPIOption {
	return func(c *UserConsentSubscriptionDataRetrievalAPIController) {
		c.errorHandler = h
	}
}

// NewUserConsentSubscriptionDataRetrievalAPIController creates a default api controller
func NewUserConsentSubscriptionDataRetrievalAPIController(s UserConsentSubscriptionDataRetrievalAPIServicer, opts ...UserConsentSubscriptionDataRetrievalAPIOption) Router {
	controller := &UserConsentSubscriptionDataRetrievalAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the UserConsentSubscriptionDataRetrievalAPIController
func (c *UserConsentSubscriptionDataRetrievalAPIController) Routes() Routes {
	return Routes{
		"GetUcData": Route{
			strings.ToUpper("Get"),
			"/nudm-sdm/v2/{supi}/uc-data",
			c.GetUcData,
		},
	}
}

// GetUcData - retrieve a UE's User Consent Subscription Data
func (c *UserConsentSubscriptionDataRetrievalAPIController) GetUcData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	supiParam := params["supi"]
	if supiParam == "" {
		c.errorHandler(w, r, &RequiredError{"supi"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	var ucPurposeParam UcPurpose
	if query.Has("uc-purpose") {
		ucPurposeParam = UcPurpose{}
		//Logically incorrect
		// query.Get("uc-purpose")
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.GetUcData(r.Context(), supiParam, supportedFeaturesParam, ucPurposeParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
