/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// SMSManagementSubscriptionDataRetrievalAPIController binds http requests to an api service and writes the service results to the http response
type SMSManagementSubscriptionDataRetrievalAPIController struct {
	service      SMSManagementSubscriptionDataRetrievalAPIServicer
	errorHandler ErrorHandler
}

// SMSManagementSubscriptionDataRetrievalAPIOption for how the controller is set up.
type SMSManagementSubscriptionDataRetrievalAPIOption func(*SMSManagementSubscriptionDataRetrievalAPIController)

// WithSMSManagementSubscriptionDataRetrievalAPIErrorHandler inject ErrorHandler into controller
func WithSMSManagementSubscriptionDataRetrievalAPIErrorHandler(h ErrorHandler) SMSManagementSubscriptionDataRetrievalAPIOption {
	return func(c *SMSManagementSubscriptionDataRetrievalAPIController) {
		c.errorHandler = h
	}
}

// NewSMSManagementSubscriptionDataRetrievalAPIController creates a default api controller
func NewSMSManagementSubscriptionDataRetrievalAPIController(s SMSManagementSubscriptionDataRetrievalAPIServicer, opts ...SMSManagementSubscriptionDataRetrievalAPIOption) Router {
	controller := &SMSManagementSubscriptionDataRetrievalAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SMSManagementSubscriptionDataRetrievalAPIController
func (c *SMSManagementSubscriptionDataRetrievalAPIController) Routes() Routes {
	return Routes{
		"GetSmsMngtData": Route{
			strings.ToUpper("Get"),
			"/nudm-sdm/v2/{supi}/sms-mng-data",
			c.GetSmsMngtData,
		},
	}
}

// GetSmsMngtData - retrieve a UE's SMS Management Subscription Data
func (c *SMSManagementSubscriptionDataRetrievalAPIController) GetSmsMngtData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	supiParam := params["supi"]
	if supiParam == "" {
		c.errorHandler(w, r, &RequiredError{"supi"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	var plmnIdParam PlmnId
	if query.Has("plmn-id") {
		plmnIdParam = PlmnId{}
		//Logically incorrect
		// query.Get("plmn-id")
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.GetSmsMngtData(r.Context(), supiParam, supportedFeaturesParam, plmnIdParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
