/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// SubscriptionDeletionAPIController binds http requests to an api service and writes the service results to the http response
type SubscriptionDeletionAPIController struct {
	service      SubscriptionDeletionAPIServicer
	errorHandler ErrorHandler
}

// SubscriptionDeletionAPIOption for how the controller is set up.
type SubscriptionDeletionAPIOption func(*SubscriptionDeletionAPIController)

// WithSubscriptionDeletionAPIErrorHandler inject ErrorHandler into controller
func WithSubscriptionDeletionAPIErrorHandler(h ErrorHandler) SubscriptionDeletionAPIOption {
	return func(c *SubscriptionDeletionAPIController) {
		c.errorHandler = h
	}
}

// NewSubscriptionDeletionAPIController creates a default api controller
func NewSubscriptionDeletionAPIController(s SubscriptionDeletionAPIServicer, opts ...SubscriptionDeletionAPIOption) Router {
	controller := &SubscriptionDeletionAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SubscriptionDeletionAPIController
func (c *SubscriptionDeletionAPIController) Routes() Routes {
	return Routes{
		"Unsubscribe": Route{
			strings.ToUpper("Delete"),
			"/nudm-sdm/v2/{ueId}/sdm-subscriptions/{subscriptionId}",
			c.Unsubscribe,
		},
	}
}

// Unsubscribe - unsubscribe from notifications
func (c *SubscriptionDeletionAPIController) Unsubscribe(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	subscriptionIdParam := params["subscriptionId"]
	if subscriptionIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subscriptionId"}, nil)
		return
	}
	result, err := c.service.Unsubscribe(r.Context(), ueIdParam, subscriptionIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
