/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// AccessTech - Represents the access technology
type AccessTech struct {
}

// AssertAccessTechRequired checks if the required fields are not zero-ed
func AssertAccessTechRequired(obj AccessTech) error {
	return nil
}

// AssertAccessTechConstraints checks if the values respects the defined constraints
func AssertAccessTechConstraints(obj AccessTech) error {
	return nil
}
