/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"os"
)



type LcsBroadcastAssistanceTypesData struct {

	// string with format 'binary' as defined in OpenAPI.
	LocationAssistanceType *os.File `json:"locationAssistanceType"`
}

// AssertLcsBroadcastAssistanceTypesDataRequired checks if the required fields are not zero-ed
func AssertLcsBroadcastAssistanceTypesDataRequired(obj LcsBroadcastAssistanceTypesData) error {
	elements := map[string]interface{}{
		"locationAssistanceType": obj.LocationAssistanceType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLcsBroadcastAssistanceTypesDataConstraints checks if the values respects the defined constraints
func AssertLcsBroadcastAssistanceTypesDataConstraints(obj LcsBroadcastAssistanceTypesData) error {
	return nil
}
