/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// RestrictionType - It contains the restriction type ALLOWED_AREAS or NOT_ALLOWED_AREAS.
type RestrictionType struct {
}

// AssertRestrictionTypeRequired checks if the required fields are not zero-ed
func AssertRestrictionTypeRequired(obj RestrictionType) error {
	return nil
}

// AssertRestrictionTypeConstraints checks if the values respects the defined constraints
func AssertRestrictionTypeConstraints(obj RestrictionType) error {
	return nil
}
