/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CagInfo struct {

	AllowedCagList []string `json:"allowedCagList"`

	CagOnlyIndicator bool `json:"cagOnlyIndicator,omitempty"`
}

// AssertCagInfoRequired checks if the required fields are not zero-ed
func AssertCagInfoRequired(obj CagInfo) error {
	elements := map[string]interface{}{
		"allowedCagList": obj.AllowedCagList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCagInfoConstraints checks if the values respects the defined constraints
func AssertCagInfoConstraints(obj CagInfo) error {
	return nil
}
