/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type SdmSubsModification struct {

	// string with format 'date-time' as defined in OpenAPI.
	Expires time.Time `json:"expires,omitempty"`

	MonitoredResourceUris []string `json:"monitoredResourceUris,omitempty"`
}

// AssertSdmSubsModificationRequired checks if the required fields are not zero-ed
func AssertSdmSubsModificationRequired(obj SdmSubsModification) error {
	return nil
}

// AssertSdmSubsModificationConstraints checks if the values respects the defined constraints
func AssertSdmSubsModificationConstraints(obj SdmSubsModification) error {
	return nil
}
