/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"errors"
)



// InterFreqTargetInfo - Indicates the Inter Frequency Target information.
type InterFreqTargetInfo struct {

	// Integer value indicating the ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR global frequency raster, as definition of \"ARFCN-ValueNR\" IE in clause 6.3.2 of 3GPP TS 38.331. 
	DlCarrierFreq int32 `json:"dlCarrierFreq"`

	// When present, this IE shall contain a list of the physical cell identities where the UE is requested to perform measurement logging for the indicated frequency. 
	CellIdList []int32 `json:"cellIdList,omitempty"`
}

// AssertInterFreqTargetInfoRequired checks if the required fields are not zero-ed
func AssertInterFreqTargetInfoRequired(obj InterFreqTargetInfo) error {
	elements := map[string]interface{}{
		"dlCarrierFreq": obj.DlCarrierFreq,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInterFreqTargetInfoConstraints checks if the values respects the defined constraints
func AssertInterFreqTargetInfoConstraints(obj InterFreqTargetInfo) error {
	if obj.DlCarrierFreq < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.DlCarrierFreq > 3279165 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
