/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ChangeType - Indicates the type of change to be performed.
type ChangeType struct {
}

// AssertChangeTypeRequired checks if the required fields are not zero-ed
func AssertChangeTypeRequired(obj ChangeType) error {
	return nil
}

// AssertChangeTypeConstraints checks if the values respects the defined constraints
func AssertChangeTypeConstraints(obj ChangeType) error {
	return nil
}
