/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Ipv6Prefix - String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952. IPv6Prefix data type may contain an individual /128 IPv6 address. 
type Ipv6Prefix struct {
}

// AssertIpv6PrefixRequired checks if the required fields are not zero-ed
func AssertIpv6PrefixRequired(obj Ipv6Prefix) error {
	return nil
}

// AssertIpv6PrefixConstraints checks if the values respects the defined constraints
func AssertIpv6PrefixConstraints(obj Ipv6Prefix) error {
	return nil
}
