/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ReportAmountMdt - The enumeration ReportAmountMdt defines Report Amount for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.10-1. 
type ReportAmountMdt struct {
}

// AssertReportAmountMdtRequired checks if the required fields are not zero-ed
func AssertReportAmountMdtRequired(obj ReportAmountMdt) error {
	return nil
}

// AssertReportAmountMdtConstraints checks if the values respects the defined constraints
func AssertReportAmountMdtConstraints(obj ReportAmountMdt) error {
	return nil
}
