/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
	"errors"
)



type SuggestedPacketNumDl struct {

	SuggestedPacketNumDl int32 `json:"suggestedPacketNumDl"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`
}

// AssertSuggestedPacketNumDlRequired checks if the required fields are not zero-ed
func AssertSuggestedPacketNumDlRequired(obj SuggestedPacketNumDl) error {
	elements := map[string]interface{}{
		"suggestedPacketNumDl": obj.SuggestedPacketNumDl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSuggestedPacketNumDlConstraints checks if the values respects the defined constraints
func AssertSuggestedPacketNumDlConstraints(obj SuggestedPacketNumDl) error {
	if obj.SuggestedPacketNumDl < 1 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
