/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// SupiRange - A range of SUPIs (subscriber identities), either based on a numeric range, or based on regular-expression matching 
type SupiRange struct {

	Start string `json:"start,omitempty"`

	End string `json:"end,omitempty"`

	Pattern string `json:"pattern,omitempty"`
}

// AssertSupiRangeRequired checks if the required fields are not zero-ed
func AssertSupiRangeRequired(obj SupiRange) error {
	return nil
}

// AssertSupiRangeConstraints checks if the values respects the defined constraints
func AssertSupiRangeConstraints(obj SupiRange) error {
	return nil
}
