/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type UeContextInSmsfData struct {

	SmsfInfo3GppAccess SmsfInfo `json:"smsfInfo3GppAccess,omitempty"`

	SmsfInfoNon3GppAccess SmsfInfo `json:"smsfInfoNon3GppAccess,omitempty"`
}

// AssertUeContextInSmsfDataRequired checks if the required fields are not zero-ed
func AssertUeContextInSmsfDataRequired(obj UeContextInSmsfData) error {
	if err := AssertSmsfInfoRequired(obj.SmsfInfo3GppAccess); err != nil {
		return err
	}
	if err := AssertSmsfInfoRequired(obj.SmsfInfoNon3GppAccess); err != nil {
		return err
	}
	return nil
}

// AssertUeContextInSmsfDataConstraints checks if the values respects the defined constraints
func AssertUeContextInSmsfDataConstraints(obj UeContextInSmsfData) error {
	return nil
}
