/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// PreemptionCapability - The enumeration PreemptionCapability indicates the pre-emption capability of a request on other QoS flows. See clause 5.7.2.2 of 3GPP TS 23.501. It shall comply with the provisions defined in table 5.5.3.1-1. 
type PreemptionCapability struct {
}

// AssertPreemptionCapabilityRequired checks if the required fields are not zero-ed
func AssertPreemptionCapabilityRequired(obj PreemptionCapability) error {
	return nil
}

// AssertPreemptionCapabilityConstraints checks if the values respects the defined constraints
func AssertPreemptionCapabilityConstraints(obj PreemptionCapability) error {
	return nil
}
