/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// OdbPacketServices - The enumeration OdbPacketServices defines the Barring of Packet Oriented Services. See 3GPP TS 23.015 for further description. It shall comply with the provisions defined in table 5.7.3.2-1 
type OdbPacketServices struct {
}

// AssertOdbPacketServicesRequired checks if the required fields are not zero-ed
func AssertOdbPacketServicesRequired(obj OdbPacketServices) error {
	return nil
}

// AssertOdbPacketServicesConstraints checks if the values respects the defined constraints
func AssertOdbPacketServicesConstraints(obj OdbPacketServices) error {
	return nil
}
