/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// AreaScope - Contain the area based on Cells or Tracking Areas.
type AreaScope struct {

	EutraCellIdList []string `json:"eutraCellIdList,omitempty"`

	NrCellIdList []string `json:"nrCellIdList,omitempty"`

	TacList []string `json:"tacList,omitempty"`

	// A map (list of key-value pairs) where PlmnId converted to a string serves as key 
	TacInfoPerPlmn map[string]TacInfo `json:"tacInfoPerPlmn,omitempty"`
}

// AssertAreaScopeRequired checks if the required fields are not zero-ed
func AssertAreaScopeRequired(obj AreaScope) error {
	return nil
}

// AssertAreaScopeConstraints checks if the values respects the defined constraints
func AssertAreaScopeConstraints(obj AreaScope) error {
	return nil
}
