/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type AccessAndMobilitySubscriptionDataSubscribedDnnListInner struct {
}

// AssertAccessAndMobilitySubscriptionDataSubscribedDnnListInnerRequired checks if the required fields are not zero-ed
func AssertAccessAndMobilitySubscriptionDataSubscribedDnnListInnerRequired(obj AccessAndMobilitySubscriptionDataSubscribedDnnListInner) error {
	return nil
}

// AssertAccessAndMobilitySubscriptionDataSubscribedDnnListInnerConstraints checks if the values respects the defined constraints
func AssertAccessAndMobilitySubscriptionDataSubscribedDnnListInnerConstraints(obj AccessAndMobilitySubscriptionDataSubscribedDnnListInner) error {
	return nil
}
