/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// IndividualApplicationDataSubscriptionDocumentAPIController binds http requests to an api service and writes the service results to the http response
type IndividualApplicationDataSubscriptionDocumentAPIController struct {
	service      IndividualApplicationDataSubscriptionDocumentAPIServicer
	errorHandler ErrorHandler
}

// IndividualApplicationDataSubscriptionDocumentAPIOption for how the controller is set up.
type IndividualApplicationDataSubscriptionDocumentAPIOption func(*IndividualApplicationDataSubscriptionDocumentAPIController)

// WithIndividualApplicationDataSubscriptionDocumentAPIErrorHandler inject ErrorHandler into controller
func WithIndividualApplicationDataSubscriptionDocumentAPIErrorHandler(h ErrorHandler) IndividualApplicationDataSubscriptionDocumentAPIOption {
	return func(c *IndividualApplicationDataSubscriptionDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewIndividualApplicationDataSubscriptionDocumentAPIController creates a default api controller
func NewIndividualApplicationDataSubscriptionDocumentAPIController(s IndividualApplicationDataSubscriptionDocumentAPIServicer, opts ...IndividualApplicationDataSubscriptionDocumentAPIOption) Router {
	controller := &IndividualApplicationDataSubscriptionDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the IndividualApplicationDataSubscriptionDocumentAPIController
func (c *IndividualApplicationDataSubscriptionDocumentAPIController) Routes() Routes {
	return Routes{
		"DeleteIndividualApplicationDataSubscription": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/application-data/subs-to-notify/{subsId}",
			c.DeleteIndividualApplicationDataSubscription,
		},
		"ReadIndividualApplicationDataSubscription": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/application-data/subs-to-notify/{subsId}",
			c.ReadIndividualApplicationDataSubscription,
		},
		"ReplaceIndividualApplicationDataSubscription": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/application-data/subs-to-notify/{subsId}",
			c.ReplaceIndividualApplicationDataSubscription,
		},
	}
}

// DeleteIndividualApplicationDataSubscription - Delete the individual Application Data subscription
func (c *IndividualApplicationDataSubscriptionDocumentAPIController) DeleteIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	result, err := c.service.DeleteIndividualApplicationDataSubscription(r.Context(), subsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ReadIndividualApplicationDataSubscription - Get an existing individual Application Data Subscription resource
func (c *IndividualApplicationDataSubscriptionDocumentAPIController) ReadIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	result, err := c.service.ReadIndividualApplicationDataSubscription(r.Context(), subsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ReplaceIndividualApplicationDataSubscription - Modify a subscription to receive notification of application data changes
func (c *IndividualApplicationDataSubscriptionDocumentAPIController) ReplaceIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	applicationDataSubsParam := ApplicationDataSubs{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&applicationDataSubsParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertApplicationDataSubsRequired(applicationDataSubsParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertApplicationDataSubsConstraints(applicationDataSubsParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ReplaceIndividualApplicationDataSubscription(r.Context(), subsIdParam, applicationDataSubsParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
