/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// PFDDataStoreAPIController binds http requests to an api service and writes the service results to the http response
type PFDDataStoreAPIController struct {
	service      PFDDataStoreAPIServicer
	errorHandler ErrorHandler
}

// PFDDataStoreAPIOption for how the controller is set up.
type PFDDataStoreAPIOption func(*PFDDataStoreAPIController)

// WithPFDDataStoreAPIErrorHandler inject ErrorHandler into controller
func WithPFDDataStoreAPIErrorHandler(h ErrorHandler) PFDDataStoreAPIOption {
	return func(c *PFDDataStoreAPIController) {
		c.errorHandler = h
	}
}

// NewPFDDataStoreAPIController creates a default api controller
func NewPFDDataStoreAPIController(s PFDDataStoreAPIServicer, opts ...PFDDataStoreAPIOption) Router {
	controller := &PFDDataStoreAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the PFDDataStoreAPIController
func (c *PFDDataStoreAPIController) Routes() Routes {
	return Routes{
		"ReadPFDData": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/application-data/pfds",
			c.ReadPFDData,
		},
	}
}

// ReadPFDData - Retrieve PFDs for application identifier(s)
func (c *PFDDataStoreAPIController) ReadPFDData(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	var appIdParam []string
	if query.Has("appId") {
		appIdParam = strings.Split(query.Get("appId"), ",")
	}
	var suppFeatParam string
	if query.Has("supp-feat") {
		suppFeatParam = query.Get("supp-feat")
	}
	result, err := c.service.ReadPFDData(r.Context(), appIdParam, suppFeatParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
