/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// IPSMGWRegistrationDocumentAPIController binds http requests to an api service and writes the service results to the http response
type IPSMGWRegistrationDocumentAPIController struct {
	service      IPSMGWRegistrationDocumentAPIServicer
	errorHandler ErrorHandler
}

// IPSMGWRegistrationDocumentAPIOption for how the controller is set up.
type IPSMGWRegistrationDocumentAPIOption func(*IPSMGWRegistrationDocumentAPIController)

// WithIPSMGWRegistrationDocumentAPIErrorHandler inject ErrorHandler into controller
func WithIPSMGWRegistrationDocumentAPIErrorHandler(h ErrorHandler) IPSMGWRegistrationDocumentAPIOption {
	return func(c *IPSMGWRegistrationDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewIPSMGWRegistrationDocumentAPIController creates a default api controller
func NewIPSMGWRegistrationDocumentAPIController(s IPSMGWRegistrationDocumentAPIServicer, opts ...IPSMGWRegistrationDocumentAPIOption) Router {
	controller := &IPSMGWRegistrationDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the IPSMGWRegistrationDocumentAPIController
func (c *IPSMGWRegistrationDocumentAPIController) Routes() Routes {
	return Routes{
		"CreateIpSmGwContext": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/ip-sm-gw",
			c.CreateIpSmGwContext,
		},
		"DeleteIpSmGwContext": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/ip-sm-gw",
			c.DeleteIpSmGwContext,
		},
		"ModifyIpSmGwContext": Route{
			strings.ToUpper("Patch"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/ip-sm-gw",
			c.ModifyIpSmGwContext,
		},
		"QueryIpSmGwContext": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/ip-sm-gw",
			c.QueryIpSmGwContext,
		},
	}
}

// CreateIpSmGwContext - Create the IP-SM-GW context data of a UE
func (c *IPSMGWRegistrationDocumentAPIController) CreateIpSmGwContext(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	ipSmGwRegistrationParam := IpSmGwRegistration{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&ipSmGwRegistrationParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertIpSmGwRegistrationRequired(ipSmGwRegistrationParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertIpSmGwRegistrationConstraints(ipSmGwRegistrationParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateIpSmGwContext(r.Context(), ueIdParam, ipSmGwRegistrationParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteIpSmGwContext - To remove the IP-SM-GW context data of a UE
func (c *IPSMGWRegistrationDocumentAPIController) DeleteIpSmGwContext(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	result, err := c.service.DeleteIpSmGwContext(r.Context(), ueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ModifyIpSmGwContext - Modify the IP-SM-GW context data of a UE
func (c *IPSMGWRegistrationDocumentAPIController) ModifyIpSmGwContext(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	patchItemParam := []PatchItem{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&patchItemParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	for _, el := range patchItemParam {
		if err := AssertPatchItemRequired(el); err != nil {
			c.errorHandler(w, r, err, nil)
			return
		}
	}
	result, err := c.service.ModifyIpSmGwContext(r.Context(), ueIdParam, patchItemParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// QueryIpSmGwContext - Retrieves the IP-SM-GW context data of a UE
func (c *IPSMGWRegistrationDocumentAPIController) QueryIpSmGwContext(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	var fieldsParam []string
	if query.Has("fields") {
		fieldsParam = strings.Split(query.Get("fields"), ",")
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.QueryIpSmGwContext(r.Context(), ueIdParam, fieldsParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
