/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// AmfSubscriptionInfoDocumentAPIController binds http requests to an api service and writes the service results to the http response
type AmfSubscriptionInfoDocumentAPIController struct {
	service      AmfSubscriptionInfoDocumentAPIServicer
	errorHandler ErrorHandler
}

// AmfSubscriptionInfoDocumentAPIOption for how the controller is set up.
type AmfSubscriptionInfoDocumentAPIOption func(*AmfSubscriptionInfoDocumentAPIController)

// WithAmfSubscriptionInfoDocumentAPIErrorHandler inject ErrorHandler into controller
func WithAmfSubscriptionInfoDocumentAPIErrorHandler(h ErrorHandler) AmfSubscriptionInfoDocumentAPIOption {
	return func(c *AmfSubscriptionInfoDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewAmfSubscriptionInfoDocumentAPIController creates a default api controller
func NewAmfSubscriptionInfoDocumentAPIController(s AmfSubscriptionInfoDocumentAPIServicer, opts ...AmfSubscriptionInfoDocumentAPIOption) Router {
	controller := &AmfSubscriptionInfoDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AmfSubscriptionInfoDocumentAPIController
func (c *AmfSubscriptionInfoDocumentAPIController) Routes() Routes {
	return Routes{
		"ModifyAmfGroupSubscriptions": Route{
			strings.ToUpper("Patch"),
			"/nudr-dr/v2/subscription-data/group-data/{ueGroupId}/ee-subscriptions/{subsId}/amf-subscriptions",
			c.ModifyAmfGroupSubscriptions,
		},
		"ModifyAmfSubscriptionInfo": Route{
			strings.ToUpper("Patch"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/ee-subscriptions/{subsId}/amf-subscriptions",
			c.ModifyAmfSubscriptionInfo,
		},
	}
}

// ModifyAmfGroupSubscriptions - modify the AMF Subscription Info
func (c *AmfSubscriptionInfoDocumentAPIController) ModifyAmfGroupSubscriptions(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueGroupIdParam := params["ueGroupId"]
	if ueGroupIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueGroupId"}, nil)
		return
	}
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	patchItemParam := []PatchItem{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&patchItemParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	for _, el := range patchItemParam {
		if err := AssertPatchItemRequired(el); err != nil {
			c.errorHandler(w, r, err, nil)
			return
		}
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.ModifyAmfGroupSubscriptions(r.Context(), ueGroupIdParam, subsIdParam, patchItemParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ModifyAmfSubscriptionInfo - modify the AMF Subscription Info
func (c *AmfSubscriptionInfoDocumentAPIController) ModifyAmfSubscriptionInfo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	patchItemParam := []PatchItem{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&patchItemParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	for _, el := range patchItemParam {
		if err := AssertPatchItemRequired(el); err != nil {
			c.errorHandler(w, r, err, nil)
			return
		}
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.ModifyAmfSubscriptionInfo(r.Context(), ueIdParam, subsIdParam, patchItemParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
