/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// IndividualServiceParameterDataDocumentAPIController binds http requests to an api service and writes the service results to the http response
type IndividualServiceParameterDataDocumentAPIController struct {
	service      IndividualServiceParameterDataDocumentAPIServicer
	errorHandler ErrorHandler
}

// IndividualServiceParameterDataDocumentAPIOption for how the controller is set up.
type IndividualServiceParameterDataDocumentAPIOption func(*IndividualServiceParameterDataDocumentAPIController)

// WithIndividualServiceParameterDataDocumentAPIErrorHandler inject ErrorHandler into controller
func WithIndividualServiceParameterDataDocumentAPIErrorHandler(h ErrorHandler) IndividualServiceParameterDataDocumentAPIOption {
	return func(c *IndividualServiceParameterDataDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewIndividualServiceParameterDataDocumentAPIController creates a default api controller
func NewIndividualServiceParameterDataDocumentAPIController(s IndividualServiceParameterDataDocumentAPIServicer, opts ...IndividualServiceParameterDataDocumentAPIOption) Router {
	controller := &IndividualServiceParameterDataDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the IndividualServiceParameterDataDocumentAPIController
func (c *IndividualServiceParameterDataDocumentAPIController) Routes() Routes {
	return Routes{
		"CreateOrReplaceServiceParameterData": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/application-data/serviceParamData/{serviceParamId}",
			c.CreateOrReplaceServiceParameterData,
		},
		"DeleteIndividualServiceParameterData": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/application-data/serviceParamData/{serviceParamId}",
			c.DeleteIndividualServiceParameterData,
		},
		"UpdateIndividualServiceParameterData": Route{
			strings.ToUpper("Patch"),
			"/nudr-dr/v2/application-data/serviceParamData/{serviceParamId}",
			c.UpdateIndividualServiceParameterData,
		},
	}
}

// CreateOrReplaceServiceParameterData - Create or update an individual Service Parameter Data resource
func (c *IndividualServiceParameterDataDocumentAPIController) CreateOrReplaceServiceParameterData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	serviceParamIdParam := params["serviceParamId"]
	if serviceParamIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"serviceParamId"}, nil)
		return
	}
	serviceParameterDataParam := ServiceParameterData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&serviceParameterDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertServiceParameterDataRequired(serviceParameterDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertServiceParameterDataConstraints(serviceParameterDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateOrReplaceServiceParameterData(r.Context(), serviceParamIdParam, serviceParameterDataParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteIndividualServiceParameterData - Delete an individual Service Parameter Data resource
func (c *IndividualServiceParameterDataDocumentAPIController) DeleteIndividualServiceParameterData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	serviceParamIdParam := params["serviceParamId"]
	if serviceParamIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"serviceParamId"}, nil)
		return
	}
	result, err := c.service.DeleteIndividualServiceParameterData(r.Context(), serviceParamIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateIndividualServiceParameterData - Modify part of the properties of an individual Service Parameter Data resource
func (c *IndividualServiceParameterDataDocumentAPIController) UpdateIndividualServiceParameterData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	serviceParamIdParam := params["serviceParamId"]
	if serviceParamIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"serviceParamId"}, nil)
		return
	}
	serviceParameterDataPatchParam := ServiceParameterDataPatch{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&serviceParameterDataPatchParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertServiceParameterDataPatchRequired(serviceParameterDataPatchParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertServiceParameterDataPatchConstraints(serviceParameterDataPatchParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateIndividualServiceParameterData(r.Context(), serviceParamIdParam, serviceParameterDataPatchParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
