/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// AMFNon3GPPAccessRegistrationDocumentAPIService is a service that implements the logic for the AMFNon3GPPAccessRegistrationDocumentAPIServicer
// This service should implement the business logic for every endpoint for the AMFNon3GPPAccessRegistrationDocumentAPI API.
// Include any external packages or services that will be required by this service.
type AMFNon3GPPAccessRegistrationDocumentAPIService struct {
}

// NewAMFNon3GPPAccessRegistrationDocumentAPIService creates a default api service
func NewAMFNon3GPPAccessRegistrationDocumentAPIService() AMFNon3GPPAccessRegistrationDocumentAPIServicer {
	return &AMFNon3GPPAccessRegistrationDocumentAPIService{}
}

// AmfContextNon3gpp - To modify the AMF context data of a UE using non 3gpp access in the UDR
func (s *AMFNon3GPPAccessRegistrationDocumentAPIService) AmfContextNon3gpp(ctx context.Context, ueId string, patchItem []PatchItem, supportedFeatures string) (ImplResponse, error) {
	// TODO - update AmfContextNon3gpp with the required logic for this service method.
	// Add api_amf_non3_gpp_access_registration_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(200, PatchResult{}) or use other options such as http.Ok ...
	// return Response(200, PatchResult{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AmfContextNon3gpp method not implemented")
}

// CreateAmfContextNon3gpp - To store the AMF context data of a UE using non-3gpp access in the UDR
func (s *AMFNon3GPPAccessRegistrationDocumentAPIService) CreateAmfContextNon3gpp(ctx context.Context, ueId string, amfNon3GppAccessRegistration AmfNon3GppAccessRegistration) (ImplResponse, error) {
	// TODO - update CreateAmfContextNon3gpp with the required logic for this service method.
	// Add api_amf_non3_gpp_access_registration_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(201, Amf3GppAccessRegistration{}) or use other options such as http.Ok ...
	// return Response(201, Amf3GppAccessRegistration{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateAmfContextNon3gpp method not implemented")
}

// QueryAmfContextNon3gpp - Retrieves the AMF context data of a UE using non-3gpp access
func (s *AMFNon3GPPAccessRegistrationDocumentAPIService) QueryAmfContextNon3gpp(ctx context.Context, ueId string, fields []string, supportedFeatures string) (ImplResponse, error) {
	// TODO - update QueryAmfContextNon3gpp with the required logic for this service method.
	// Add api_amf_non3_gpp_access_registration_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AmfNon3GppAccessRegistration{}) or use other options such as http.Ok ...
	// return Response(200, AmfNon3GppAccessRegistration{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryAmfContextNon3gpp method not implemented")
}
