/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// SMSManagementSubscriptionDataDocumentAPIService is a service that implements the logic for the SMSManagementSubscriptionDataDocumentAPIServicer
// This service should implement the business logic for every endpoint for the SMSManagementSubscriptionDataDocumentAPI API.
// Include any external packages or services that will be required by this service.
type SMSManagementSubscriptionDataDocumentAPIService struct {
}

// NewSMSManagementSubscriptionDataDocumentAPIService creates a default api service
func NewSMSManagementSubscriptionDataDocumentAPIService() SMSManagementSubscriptionDataDocumentAPIServicer {
	return &SMSManagementSubscriptionDataDocumentAPIService{}
}

// QuerySmsMngData - Retrieves the SMS management subscription data of a UE
func (s *SMSManagementSubscriptionDataDocumentAPIService) QuerySmsMngData(ctx context.Context, ueId string, servingPlmnId string, supportedFeatures string, ifNoneMatch string, ifModifiedSince string) (ImplResponse, error) {
	// TODO - update QuerySmsMngData with the required logic for this service method.
	// Add api_sms_management_subscription_data_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SmsManagementSubscriptionData{}) or use other options such as http.Ok ...
	// return Response(200, SmsManagementSubscriptionData{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QuerySmsMngData method not implemented")
}
