/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// AuthenticationUPUDocumentAPIController binds http requests to an api service and writes the service results to the http response
type AuthenticationUPUDocumentAPIController struct {
	service      AuthenticationUPUDocumentAPIServicer
	errorHandler ErrorHandler
}

// AuthenticationUPUDocumentAPIOption for how the controller is set up.
type AuthenticationUPUDocumentAPIOption func(*AuthenticationUPUDocumentAPIController)

// WithAuthenticationUPUDocumentAPIErrorHandler inject ErrorHandler into controller
func WithAuthenticationUPUDocumentAPIErrorHandler(h ErrorHandler) AuthenticationUPUDocumentAPIOption {
	return func(c *AuthenticationUPUDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewAuthenticationUPUDocumentAPIController creates a default api controller
func NewAuthenticationUPUDocumentAPIController(s AuthenticationUPUDocumentAPIServicer, opts ...AuthenticationUPUDocumentAPIOption) Router {
	controller := &AuthenticationUPUDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuthenticationUPUDocumentAPIController
func (c *AuthenticationUPUDocumentAPIController) Routes() Routes {
	return Routes{
		"CreateAuthenticationUPU": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/subscription-data/{ueId}/ue-update-confirmation-data/upu-data",
			c.CreateAuthenticationUPU,
		},
		"QueryAuthUPU": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/ue-update-confirmation-data/upu-data",
			c.QueryAuthUPU,
		},
	}
}

// CreateAuthenticationUPU - To store the UPU acknowledgement information of a UE
func (c *AuthenticationUPUDocumentAPIController) CreateAuthenticationUPU(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	upuDataParam := UpuData{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&upuDataParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUpuDataRequired(upuDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUpuDataConstraints(upuDataParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.CreateAuthenticationUPU(r.Context(), ueIdParam, upuDataParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// QueryAuthUPU - Retrieves the UPU acknowledgement information of a UE
func (c *AuthenticationUPUDocumentAPIController) QueryAuthUPU(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.QueryAuthUPU(r.Context(), ueIdParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
