/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// SubsToNotifyCollectionAPIService is a service that implements the logic for the SubsToNotifyCollectionAPIServicer
// This service should implement the business logic for every endpoint for the SubsToNotifyCollectionAPI API.
// Include any external packages or services that will be required by this service.
type SubsToNotifyCollectionAPIService struct {
}

// NewSubsToNotifyCollectionAPIService creates a default api service
func NewSubsToNotifyCollectionAPIService() SubsToNotifyCollectionAPIServicer {
	return &SubsToNotifyCollectionAPIService{}
}

// QuerySubsToNotify - Retrieves the list of subscriptions
func (s *SubsToNotifyCollectionAPIService) QuerySubsToNotify(ctx context.Context, ueId string, supportedFeatures string) (ImplResponse, error) {
	// TODO - update QuerySubsToNotify with the required logic for this service method.
	// Add api_subs_to_notify_collection_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []SubscriptionDataSubscriptions{}) or use other options such as http.Ok ...
	// return Response(200, []SubscriptionDataSubscriptions{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QuerySubsToNotify method not implemented")
}

// RemoveMultipleSubscriptionDataSubscriptions - Deletes subscriptions identified by a given ue-id parameter
func (s *SubsToNotifyCollectionAPIService) RemoveMultipleSubscriptionDataSubscriptions(ctx context.Context, ueId string, nfInstanceId string, deleteAllNfs bool, implicitUnsubscribeIndication bool) (ImplResponse, error) {
	// TODO - update RemoveMultipleSubscriptionDataSubscriptions with the required logic for this service method.
	// Add api_subs_to_notify_collection_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RemoveMultipleSubscriptionDataSubscriptions method not implemented")
}

// SubscriptionDataSubscriptions - Subscription data subscriptions
func (s *SubsToNotifyCollectionAPIService) SubscriptionDataSubscription(ctx context.Context, subscriptionDataSubscriptions SubscriptionDataSubscriptions) (ImplResponse, error) {
	// TODO - update SubscriptionDataSubscriptions with the required logic for this service method.
	// Add api_subs_to_notify_collection_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// Return a response with the createdSubscription (dummy data)
	return Response(http.StatusCreated, SubscriptionDataSubscriptions{}), nil
	// TODO: Uncomment the next line to return response Response(201, SubscriptionDataSubscriptions{}) or use other options such as http.Ok ...
	// return Response(201, SubscriptionDataSubscriptions{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	// return Response(http.StatusNotImplemented, nil), errors.New("SubscriptionDataSubscriptions method not implemented")
}
