/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// Delete5GVnGroupAPIController binds http requests to an api service and writes the service results to the http response
type Delete5GVnGroupAPIController struct {
	service      Delete5GVnGroupAPIServicer
	errorHandler ErrorHandler
}

// Delete5GVnGroupAPIOption for how the controller is set up.
type Delete5GVnGroupAPIOption func(*Delete5GVnGroupAPIController)

// WithDelete5GVnGroupAPIErrorHandler inject ErrorHandler into controller
func WithDelete5GVnGroupAPIErrorHandler(h ErrorHandler) Delete5GVnGroupAPIOption {
	return func(c *Delete5GVnGroupAPIController) {
		c.errorHandler = h
	}
}

// NewDelete5GVnGroupAPIController creates a default api controller
func NewDelete5GVnGroupAPIController(s Delete5GVnGroupAPIServicer, opts ...Delete5GVnGroupAPIOption) Router {
	controller := &Delete5GVnGroupAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the Delete5GVnGroupAPIController
func (c *Delete5GVnGroupAPIController) Routes() Routes {
	return Routes{
		"Delete5GVnGroup": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/subscription-data/group-data/5g-vn-groups/{externalGroupId}",
			c.Delete5GVnGroup,
		},
	}
}

// Delete5GVnGroup - Deletes the 5GVnGroup
func (c *Delete5GVnGroupAPIController) Delete5GVnGroup(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	externalGroupIdParam := params["externalGroupId"]
	if externalGroupIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"externalGroupId"}, nil)
		return
	}
	result, err := c.service.Delete5GVnGroup(r.Context(), externalGroupIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
