/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// AccessAndMobilitySubscriptionDataDocumentAPIService is a service that implements the logic for the AccessAndMobilitySubscriptionDataDocumentAPIServicer
// This service should implement the business logic for every endpoint for the AccessAndMobilitySubscriptionDataDocumentAPI API.
// Include any external packages or services that will be required by this service.
type AccessAndMobilitySubscriptionDataDocumentAPIService struct {
}

// NewAccessAndMobilitySubscriptionDataDocumentAPIService creates a default api service
func NewAccessAndMobilitySubscriptionDataDocumentAPIService() AccessAndMobilitySubscriptionDataDocumentAPIServicer {
	return &AccessAndMobilitySubscriptionDataDocumentAPIService{}
}

// QueryAmData - Retrieves the access and mobility subscription data of a UE
func (s *AccessAndMobilitySubscriptionDataDocumentAPIService) QueryAmData(ctx context.Context, ueId string, servingPlmnId string, fields []string, supportedFeatures string, ifNoneMatch string, ifModifiedSince string) (ImplResponse, error) {
	// TODO - update QueryAmData with the required logic for this service method.
	// Add api_access_and_mobility_subscription_data_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccessAndMobilitySubscriptionData{}) or use other options such as http.Ok ...
	// return Response(200, AccessAndMobilitySubscriptionData{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryAmData method not implemented")
}
