/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// EventExposureSubscriptionDocumentAPIService is a service that implements the logic for the EventExposureSubscriptionDocumentAPIServicer
// This service should implement the business logic for every endpoint for the EventExposureSubscriptionDocumentAPI API.
// Include any external packages or services that will be required by this service.
type EventExposureSubscriptionDocumentAPIService struct {
}

// NewEventExposureSubscriptionDocumentAPIService creates a default api service
func NewEventExposureSubscriptionDocumentAPIService() EventExposureSubscriptionDocumentAPIServicer {
	return &EventExposureSubscriptionDocumentAPIService{}
}

// ModifyEesubscription - Modify an individual ee subscription of a UE
func (s *EventExposureSubscriptionDocumentAPIService) ModifyEesubscription(ctx context.Context, ueId string, subsId string, patchItem []PatchItem, supportedFeatures string) (ImplResponse, error) {
	// TODO - update ModifyEesubscription with the required logic for this service method.
	// Add api_event_exposure_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(200, PatchResult{}) or use other options such as http.Ok ...
	// return Response(200, PatchResult{}), nil

	// TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(403, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ModifyEesubscription method not implemented")
}

// QueryeeSubscription - Retrieve a eeSubscription
func (s *EventExposureSubscriptionDocumentAPIService) QueryeeSubscription(ctx context.Context, ueId string, subsId string) (ImplResponse, error) {
	// TODO - update QueryeeSubscription with the required logic for this service method.
	// Add api_event_exposure_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	// return Response(200, map[string]interface{}{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryeeSubscription method not implemented")
}

// RemoveeeSubscriptions - Deletes a eeSubscription
func (s *EventExposureSubscriptionDocumentAPIService) RemoveeeSubscriptions(ctx context.Context, ueId string, subsId string) (ImplResponse, error) {
	// TODO - update RemoveeeSubscriptions with the required logic for this service method.
	// Add api_event_exposure_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RemoveeeSubscriptions method not implemented")
}

// UpdateEesubscriptions - Update an individual ee subscriptions of a UE
func (s *EventExposureSubscriptionDocumentAPIService) UpdateEesubscriptions(ctx context.Context, ueId string, subsId string, eeSubscription EeSubscription) (ImplResponse, error) {
	// TODO - update UpdateEesubscriptions with the required logic for this service method.
	// Add api_event_exposure_subscription_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	// return Response(404, ProblemDetails{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateEesubscriptions method not implemented")
}
