/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// EventExposureDataDocumentAPIController binds http requests to an api service and writes the service results to the http response
type EventExposureDataDocumentAPIController struct {
	service      EventExposureDataDocumentAPIServicer
	errorHandler ErrorHandler
}

// EventExposureDataDocumentAPIOption for how the controller is set up.
type EventExposureDataDocumentAPIOption func(*EventExposureDataDocumentAPIController)

// WithEventExposureDataDocumentAPIErrorHandler inject ErrorHandler into controller
func WithEventExposureDataDocumentAPIErrorHandler(h ErrorHandler) EventExposureDataDocumentAPIOption {
	return func(c *EventExposureDataDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewEventExposureDataDocumentAPIController creates a default api controller
func NewEventExposureDataDocumentAPIController(s EventExposureDataDocumentAPIServicer, opts ...EventExposureDataDocumentAPIOption) Router {
	controller := &EventExposureDataDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the EventExposureDataDocumentAPIController
func (c *EventExposureDataDocumentAPIController) Routes() Routes {
	return Routes{
		"QueryEEData": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/ee-profile-data",
			c.QueryEEData,
		},
	}
}

// QueryEEData - Retrieves the ee profile data of a UE
func (c *EventExposureDataDocumentAPIController) QueryEEData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	var fieldsParam []string
	if query.Has("fields") {
		fieldsParam = strings.Split(query.Get("fields"), ",")
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.QueryEEData(r.Context(), ueIdParam, fieldsParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
