/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// Delete5GVnGroupAPIService is a service that implements the logic for the Delete5GVnGroupAPIServicer
// This service should implement the business logic for every endpoint for the Delete5GVnGroupAPI API.
// Include any external packages or services that will be required by this service.
type Delete5GVnGroupAPIService struct {
}

// NewDelete5GVnGroupAPIService creates a default api service
func NewDelete5GVnGroupAPIService() Delete5GVnGroupAPIServicer {
	return &Delete5GVnGroupAPIService{}
}

// Delete5GVnGroup - Deletes the 5GVnGroup
func (s *Delete5GVnGroupAPIService) Delete5GVnGroup(ctx context.Context, externalGroupId string) (ImplResponse, error) {
	// TODO - update Delete5GVnGroup with the required logic for this service method.
	// Add api_delete5_gvn_group_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Delete5GVnGroup method not implemented")
}
