/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// OperatorSpecificDataContainerDocumentAPIController binds http requests to an api service and writes the service results to the http response
type OperatorSpecificDataContainerDocumentAPIController struct {
	service      OperatorSpecificDataContainerDocumentAPIServicer
	errorHandler ErrorHandler
}

// OperatorSpecificDataContainerDocumentAPIOption for how the controller is set up.
type OperatorSpecificDataContainerDocumentAPIOption func(*OperatorSpecificDataContainerDocumentAPIController)

// WithOperatorSpecificDataContainerDocumentAPIErrorHandler inject ErrorHandler into controller
func WithOperatorSpecificDataContainerDocumentAPIErrorHandler(h ErrorHandler) OperatorSpecificDataContainerDocumentAPIOption {
	return func(c *OperatorSpecificDataContainerDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewOperatorSpecificDataContainerDocumentAPIController creates a default api controller
func NewOperatorSpecificDataContainerDocumentAPIController(s OperatorSpecificDataContainerDocumentAPIServicer, opts ...OperatorSpecificDataContainerDocumentAPIOption) Router {
	controller := &OperatorSpecificDataContainerDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the OperatorSpecificDataContainerDocumentAPIController
func (c *OperatorSpecificDataContainerDocumentAPIController) Routes() Routes {
	return Routes{
		"CreateOperSpecData": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/subscription-data/{ueId}/operator-specific-data",
			c.CreateOperSpecData,
		},
		"DeleteOperSpecData": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/subscription-data/{ueId}/operator-specific-data",
			c.DeleteOperSpecData,
		},
		"ModifyOperSpecData": Route{
			strings.ToUpper("Patch"),
			"/nudr-dr/v2/subscription-data/{ueId}/operator-specific-data",
			c.ModifyOperSpecData,
		},
		"QueryOperSpecData": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/operator-specific-data",
			c.QueryOperSpecData,
		},
	}
}

// CreateOperSpecData - To create an operator-specific data resource of a UE
func (c *OperatorSpecificDataContainerDocumentAPIController) CreateOperSpecData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	requestBodyParam := map[string]OperatorSpecificDataContainer{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&requestBodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.CreateOperSpecData(r.Context(), ueIdParam, requestBodyParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteOperSpecData - To remove an operator-specific data resource of a UE
func (c *OperatorSpecificDataContainerDocumentAPIController) DeleteOperSpecData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	result, err := c.service.DeleteOperSpecData(r.Context(), ueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ModifyOperSpecData - To modify operator specific data of a UE
func (c *OperatorSpecificDataContainerDocumentAPIController) ModifyOperSpecData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	patchItemParam := []PatchItem{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&patchItemParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	for _, el := range patchItemParam {
		if err := AssertPatchItemRequired(el); err != nil {
			c.errorHandler(w, r, err, nil)
			return
		}
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.ModifyOperSpecData(r.Context(), ueIdParam, patchItemParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// QueryOperSpecData - Retrieves the operator specific data of a UE
func (c *OperatorSpecificDataContainerDocumentAPIController) QueryOperSpecData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	var fieldsParam []string
	if query.Has("fields") {
		fieldsParam = strings.Split(query.Get("fields"), ",")
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.QueryOperSpecData(r.Context(), ueIdParam, fieldsParam, supportedFeaturesParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
