/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// Class5GMBSGroupsInternalDocumentAPIController binds http requests to an api service and writes the service results to the http response
type Class5GMBSGroupsInternalDocumentAPIController struct {
	service      Class5GMBSGroupsInternalDocumentAPIServicer
	errorHandler ErrorHandler
}

// Class5GMBSGroupsInternalDocumentAPIOption for how the controller is set up.
type Class5GMBSGroupsInternalDocumentAPIOption func(*Class5GMBSGroupsInternalDocumentAPIController)

// WithClass5GMBSGroupsInternalDocumentAPIErrorHandler inject ErrorHandler into controller
func WithClass5GMBSGroupsInternalDocumentAPIErrorHandler(h ErrorHandler) Class5GMBSGroupsInternalDocumentAPIOption {
	return func(c *Class5GMBSGroupsInternalDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewClass5GMBSGroupsInternalDocumentAPIController creates a default api controller
func NewClass5GMBSGroupsInternalDocumentAPIController(s Class5GMBSGroupsInternalDocumentAPIServicer, opts ...Class5GMBSGroupsInternalDocumentAPIOption) Router {
	controller := &Class5GMBSGroupsInternalDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the Class5GMBSGroupsInternalDocumentAPIController
func (c *Class5GMBSGroupsInternalDocumentAPIController) Routes() Routes {
	return Routes{
		"Query5GMbsGroupInternal": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/group-data/mbs-group-membership/internal",
			c.Query5GMbsGroupInternal,
		},
	}
}

// Query5GMbsGroupInternal - Retrieves the data of 5G MBS Group
func (c *Class5GMBSGroupsInternalDocumentAPIController) Query5GMbsGroupInternal(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	var internalGroupIdsParam []string
	if query.Has("internal-group-ids") {
		internalGroupIdsParam = strings.Split(query.Get("internal-group-ids"), ",")
	}
	result, err := c.service.Query5GMbsGroupInternal(r.Context(), internalGroupIdsParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
