/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// HSSSDMSubscriptionInfoDocumentAPIController binds http requests to an api service and writes the service results to the http response
type HSSSDMSubscriptionInfoDocumentAPIController struct {
	service      HSSSDMSubscriptionInfoDocumentAPIServicer
	errorHandler ErrorHandler
}

// HSSSDMSubscriptionInfoDocumentAPIOption for how the controller is set up.
type HSSSDMSubscriptionInfoDocumentAPIOption func(*HSSSDMSubscriptionInfoDocumentAPIController)

// WithHSSSDMSubscriptionInfoDocumentAPIErrorHandler inject ErrorHandler into controller
func WithHSSSDMSubscriptionInfoDocumentAPIErrorHandler(h ErrorHandler) HSSSDMSubscriptionInfoDocumentAPIOption {
	return func(c *HSSSDMSubscriptionInfoDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewHSSSDMSubscriptionInfoDocumentAPIController creates a default api controller
func NewHSSSDMSubscriptionInfoDocumentAPIController(s HSSSDMSubscriptionInfoDocumentAPIServicer, opts ...HSSSDMSubscriptionInfoDocumentAPIOption) Router {
	controller := &HSSSDMSubscriptionInfoDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the HSSSDMSubscriptionInfoDocumentAPIController
func (c *HSSSDMSubscriptionInfoDocumentAPIController) Routes() Routes {
	return Routes{
		"CreateHSSSDMSubscriptions": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/sdm-subscriptions/{subsId}/hss-sdm-subscriptions",
			c.CreateHSSSDMSubscriptions,
		},
		"GetHssSDMSubscriptionInfo": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/sdm-subscriptions/{subsId}/hss-sdm-subscriptions",
			c.GetHssSDMSubscriptionInfo,
		},
		"ModifyHssSDMSubscriptionInfo": Route{
			strings.ToUpper("Patch"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/sdm-subscriptions/{subsId}/hss-sdm-subscriptions",
			c.ModifyHssSDMSubscriptionInfo,
		},
		"RemoveHssSDMSubscriptionsInfo": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/sdm-subscriptions/{subsId}/hss-sdm-subscriptions",
			c.RemoveHssSDMSubscriptionsInfo,
		},
	}
}

// CreateHSSSDMSubscriptions - Create HSS SDM Subscription Info
func (c *HSSSDMSubscriptionInfoDocumentAPIController) CreateHSSSDMSubscriptions(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	hssSubscriptionInfoParam := HssSubscriptionInfo{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&hssSubscriptionInfoParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertHssSubscriptionInfoRequired(hssSubscriptionInfoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertHssSubscriptionInfoConstraints(hssSubscriptionInfoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateHSSSDMSubscriptions(r.Context(), ueIdParam, subsIdParam, hssSubscriptionInfoParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetHssSDMSubscriptionInfo - Retrieve HSS SDM Subscription Info
func (c *HSSSDMSubscriptionInfoDocumentAPIController) GetHssSDMSubscriptionInfo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	result, err := c.service.GetHssSDMSubscriptionInfo(r.Context(), ueIdParam, subsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ModifyHssSDMSubscriptionInfo - Modify HSS SDM Subscription Info
func (c *HSSSDMSubscriptionInfoDocumentAPIController) ModifyHssSDMSubscriptionInfo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	patchItemParam := []PatchItem{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&patchItemParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	for _, el := range patchItemParam {
		if err := AssertPatchItemRequired(el); err != nil {
			c.errorHandler(w, r, err, nil)
			return
		}
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.ModifyHssSDMSubscriptionInfo(r.Context(), ueIdParam, subsIdParam, patchItemParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// RemoveHssSDMSubscriptionsInfo - Delete HSS SDM Subscription Info
func (c *HSSSDMSubscriptionInfoDocumentAPIController) RemoveHssSDMSubscriptionsInfo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	subsIdParam := params["subsId"]
	if subsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"subsId"}, nil)
		return
	}
	result, err := c.service.RemoveHssSDMSubscriptionsInfo(r.Context(), ueIdParam, subsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
