/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// Query5GVnGroupConfigurationDocumentAPIService is a service that implements the logic for the Query5GVnGroupConfigurationDocumentAPIServicer
// This service should implement the business logic for every endpoint for the Query5GVnGroupConfigurationDocumentAPI API.
// Include any external packages or services that will be required by this service.
type Query5GVnGroupConfigurationDocumentAPIService struct {
}

// NewQuery5GVnGroupConfigurationDocumentAPIService creates a default api service
func NewQuery5GVnGroupConfigurationDocumentAPIService() Query5GVnGroupConfigurationDocumentAPIServicer {
	return &Query5GVnGroupConfigurationDocumentAPIService{}
}

// Get5GVnGroupConfiguration - Retrieve a 5GVnGroup configuration
func (s *Query5GVnGroupConfigurationDocumentAPIService) Get5GVnGroupConfiguration(ctx context.Context, externalGroupId string) (ImplResponse, error) {
	// TODO - update Get5GVnGroupConfiguration with the required logic for this service method.
	// Add api_query5_gvn_group_configuration_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Model5GvnGroupConfiguration{}) or use other options such as http.Ok ...
	// return Response(200, Model5GvnGroupConfiguration{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Get5GVnGroupConfiguration method not implemented")
}
