/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// ContextDataDocumentAPIService is a service that implements the logic for the ContextDataDocumentAPIServicer
// This service should implement the business logic for every endpoint for the ContextDataDocumentAPI API.
// Include any external packages or services that will be required by this service.
type ContextDataDocumentAPIService struct {
}

// NewContextDataDocumentAPIService creates a default api service
func NewContextDataDocumentAPIService() ContextDataDocumentAPIServicer {
	return &ContextDataDocumentAPIService{}
}

// QueryContextData - Retrieve multiple context data sets of a UE
func (s *ContextDataDocumentAPIService) QueryContextData(ctx context.Context, ueId string, contextDatasetNames []ContextDataSetName) (ImplResponse, error) {
	// TODO - update QueryContextData with the required logic for this service method.
	// Add api_context_data_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ContextDataSets{}) or use other options such as http.Ok ...
	// return Response(200, ContextDataSets{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryContextData method not implemented")
}
