/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// LCSMobileOriginatedSubscriptionDataAPIService is a service that implements the logic for the LCSMobileOriginatedSubscriptionDataAPIServicer
// This service should implement the business logic for every endpoint for the LCSMobileOriginatedSubscriptionDataAPI API.
// Include any external packages or services that will be required by this service.
type LCSMobileOriginatedSubscriptionDataAPIService struct {
}

// NewLCSMobileOriginatedSubscriptionDataAPIService creates a default api service
func NewLCSMobileOriginatedSubscriptionDataAPIService() LCSMobileOriginatedSubscriptionDataAPIServicer {
	return &LCSMobileOriginatedSubscriptionDataAPIService{}
}

// QueryLcsMoData - Retrieves the LCS Mobile Originated subscription data of a UE
func (s *LCSMobileOriginatedSubscriptionDataAPIService) QueryLcsMoData(ctx context.Context, ueId string, fields []string, supportedFeatures string, ifNoneMatch string, ifModifiedSince string) (ImplResponse, error) {
	// TODO - update QueryLcsMoData with the required logic for this service method.
	// Add api_lcs_mobile_originated_subscription_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LcsMoData{}) or use other options such as http.Ok ...
	// return Response(200, LcsMoData{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryLcsMoData method not implemented")
}
