/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIService is a service that implements the logic for the RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIServicer
// This service should implement the business logic for every endpoint for the RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPI API.
// Include any external packages or services that will be required by this service.
type RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIService struct {
}

// NewRetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIService creates a default api service
func NewRetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIService() RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIServicer {
	return &RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIService{}
}

// QueryPeiInformation - Retrieves the PEI Information of the 5GC/EPC domains
func (s *RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIService) QueryPeiInformation(ctx context.Context, ueId string) (ImplResponse, error) {
	// TODO - update QueryPeiInformation with the required logic for this service method.
	// Add api_retrieve_the_roaming_information_of_the5_gcepc_domains_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, PeiUpdateInfo{}) or use other options such as http.Ok ...
	// return Response(200, PeiUpdateInfo{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryPeiInformation method not implemented")
}
