/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// AuthEventDocumentAPIController binds http requests to an api service and writes the service results to the http response
type AuthEventDocumentAPIController struct {
	service      AuthEventDocumentAPIServicer
	errorHandler ErrorHandler
}

// AuthEventDocumentAPIOption for how the controller is set up.
type AuthEventDocumentAPIOption func(*AuthEventDocumentAPIController)

// WithAuthEventDocumentAPIErrorHandler inject ErrorHandler into controller
func WithAuthEventDocumentAPIErrorHandler(h ErrorHandler) AuthEventDocumentAPIOption {
	return func(c *AuthEventDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewAuthEventDocumentAPIController creates a default api controller
func NewAuthEventDocumentAPIController(s AuthEventDocumentAPIServicer, opts ...AuthEventDocumentAPIOption) Router {
	controller := &AuthEventDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuthEventDocumentAPIController
func (c *AuthEventDocumentAPIController) Routes() Routes {
	return Routes{
		"DeleteAuthenticationStatus": Route{
			strings.ToUpper("Delete"),
			"/nudr-dr/v2/subscription-data/{ueId}/authentication-data/authentication-status",
			c.DeleteAuthenticationStatus,
		},
		"QueryAuthenticationStatus": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/authentication-data/authentication-status",
			c.QueryAuthenticationStatus,
		},
	}
}

// DeleteAuthenticationStatus - To remove the Authentication Status of a UE
func (c *AuthEventDocumentAPIController) DeleteAuthenticationStatus(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	result, err := c.service.DeleteAuthenticationStatus(r.Context(), ueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// QueryAuthenticationStatus - Retrieves the Authentication Status of a UE
func (c *AuthEventDocumentAPIController) QueryAuthenticationStatus(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	var fieldsParam []string
	if query.Has("fields") {
		fieldsParam = strings.Split(query.Get("fields"), ",")
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.QueryAuthenticationStatus(r.Context(), ueIdParam, fieldsParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
