/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController binds http requests to an api service and writes the service results to the http response
type RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController struct {
	service      RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIServicer
	errorHandler ErrorHandler
}

// RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIOption for how the controller is set up.
type RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIOption func(*RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController)

// WithRetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIErrorHandler inject ErrorHandler into controller
func WithRetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIErrorHandler(h ErrorHandler) RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIOption {
	return func(c *RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewRetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController creates a default api controller
func NewRetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController(s RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIServicer, opts ...RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIOption) Router {
	controller := &RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController
func (c *RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController) Routes() Routes {
	return Routes{
		"QueryPeiInformation": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/{ueId}/context-data/pei-info",
			c.QueryPeiInformation,
		},
	}
}

// QueryPeiInformation - Retrieves the PEI Information of the 5GC/EPC domains
func (c *RetrieveTheRoamingInformationOfThe5GCEPCDomainsDocumentAPIController) QueryPeiInformation(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	ueIdParam := params["ueId"]
	if ueIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueId"}, nil)
		return
	}
	result, err := c.service.QueryPeiInformation(r.Context(), ueIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
