/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// EventExposureDataForAGroupDocumentAPIController binds http requests to an api service and writes the service results to the http response
type EventExposureDataForAGroupDocumentAPIController struct {
	service      EventExposureDataForAGroupDocumentAPIServicer
	errorHandler ErrorHandler
}

// EventExposureDataForAGroupDocumentAPIOption for how the controller is set up.
type EventExposureDataForAGroupDocumentAPIOption func(*EventExposureDataForAGroupDocumentAPIController)

// WithEventExposureDataForAGroupDocumentAPIErrorHandler inject ErrorHandler into controller
func WithEventExposureDataForAGroupDocumentAPIErrorHandler(h ErrorHandler) EventExposureDataForAGroupDocumentAPIOption {
	return func(c *EventExposureDataForAGroupDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewEventExposureDataForAGroupDocumentAPIController creates a default api controller
func NewEventExposureDataForAGroupDocumentAPIController(s EventExposureDataForAGroupDocumentAPIServicer, opts ...EventExposureDataForAGroupDocumentAPIOption) Router {
	controller := &EventExposureDataForAGroupDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the EventExposureDataForAGroupDocumentAPIController
func (c *EventExposureDataForAGroupDocumentAPIController) Routes() Routes {
	return Routes{
		"QueryGroupEEData": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/group-data/{ueGroupId}/ee-profile-data",
			c.QueryGroupEEData,
		},
	}
}

// QueryGroupEEData - Retrieves the ee profile data profile data of a group or anyUE
func (c *EventExposureDataForAGroupDocumentAPIController) QueryGroupEEData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	ueGroupIdParam := params["ueGroupId"]
	if ueGroupIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"ueGroupId"}, nil)
		return
	}
	var supportedFeaturesParam string
	if query.Has("supported-features") {
		supportedFeaturesParam = query.Get("supported-features")
	}
	result, err := c.service.QueryGroupEEData(r.Context(), ueGroupIdParam, supportedFeaturesParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
