/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// MulticastMbsGroupMembDocumentAPIController binds http requests to an api service and writes the service results to the http response
type MulticastMbsGroupMembDocumentAPIController struct {
	service      MulticastMbsGroupMembDocumentAPIServicer
	errorHandler ErrorHandler
}

// MulticastMbsGroupMembDocumentAPIOption for how the controller is set up.
type MulticastMbsGroupMembDocumentAPIOption func(*MulticastMbsGroupMembDocumentAPIController)

// WithMulticastMbsGroupMembDocumentAPIErrorHandler inject ErrorHandler into controller
func WithMulticastMbsGroupMembDocumentAPIErrorHandler(h ErrorHandler) MulticastMbsGroupMembDocumentAPIOption {
	return func(c *MulticastMbsGroupMembDocumentAPIController) {
		c.errorHandler = h
	}
}

// NewMulticastMbsGroupMembDocumentAPIController creates a default api controller
func NewMulticastMbsGroupMembDocumentAPIController(s MulticastMbsGroupMembDocumentAPIServicer, opts ...MulticastMbsGroupMembDocumentAPIOption) Router {
	controller := &MulticastMbsGroupMembDocumentAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MulticastMbsGroupMembDocumentAPIController
func (c *MulticastMbsGroupMembDocumentAPIController) Routes() Routes {
	return Routes{
		"Create5GmbsGroup": Route{
			strings.ToUpper("Put"),
			"/nudr-dr/v2/subscription-data/group-data/mbs-group-membership/{externalGroupId}",
			c.Create5GmbsGroup,
		},
	}
}

// Create5GmbsGroup - Create an individual 5G MBS Grouop
func (c *MulticastMbsGroupMembDocumentAPIController) Create5GmbsGroup(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	externalGroupIdParam := params["externalGroupId"]
	if externalGroupIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"externalGroupId"}, nil)
		return
	}
	multicastMbsGroupMembParam := MulticastMbsGroupMemb{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&multicastMbsGroupMembParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertMulticastMbsGroupMembRequired(multicastMbsGroupMembParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertMulticastMbsGroupMembConstraints(multicastMbsGroupMembParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Create5GmbsGroup(r.Context(), externalGroupIdParam, multicastMbsGroupMembParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
