/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// RetrievalOfIndividualSharedDataAPIController binds http requests to an api service and writes the service results to the http response
type RetrievalOfIndividualSharedDataAPIController struct {
	service      RetrievalOfIndividualSharedDataAPIServicer
	errorHandler ErrorHandler
}

// RetrievalOfIndividualSharedDataAPIOption for how the controller is set up.
type RetrievalOfIndividualSharedDataAPIOption func(*RetrievalOfIndividualSharedDataAPIController)

// WithRetrievalOfIndividualSharedDataAPIErrorHandler inject ErrorHandler into controller
func WithRetrievalOfIndividualSharedDataAPIErrorHandler(h ErrorHandler) RetrievalOfIndividualSharedDataAPIOption {
	return func(c *RetrievalOfIndividualSharedDataAPIController) {
		c.errorHandler = h
	}
}

// NewRetrievalOfIndividualSharedDataAPIController creates a default api controller
func NewRetrievalOfIndividualSharedDataAPIController(s RetrievalOfIndividualSharedDataAPIServicer, opts ...RetrievalOfIndividualSharedDataAPIOption) Router {
	controller := &RetrievalOfIndividualSharedDataAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the RetrievalOfIndividualSharedDataAPIController
func (c *RetrievalOfIndividualSharedDataAPIController) Routes() Routes {
	return Routes{
		"GetIndividualSharedData": Route{
			strings.ToUpper("Get"),
			"/nudr-dr/v2/subscription-data/shared-data/{sharedDataId}",
			c.GetIndividualSharedData,
		},
	}
}

// GetIndividualSharedData - retrieve individual shared data
func (c *RetrievalOfIndividualSharedDataAPIController) GetIndividualSharedData(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	sharedDataIdParam := params["sharedDataId"]
	if sharedDataIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"sharedDataId"}, nil)
		return
	}
	ifNoneMatchParam := r.Header.Get("If-None-Match")
	ifModifiedSinceParam := r.Header.Get("If-Modified-Since")
	result, err := c.service.GetIndividualSharedData(r.Context(), sharedDataIdParam, ifNoneMatchParam, ifModifiedSinceParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
