/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// AuthenticationUPUDocumentAPIService is a service that implements the logic for the AuthenticationUPUDocumentAPIServicer
// This service should implement the business logic for every endpoint for the AuthenticationUPUDocumentAPI API.
// Include any external packages or services that will be required by this service.
type AuthenticationUPUDocumentAPIService struct {
}

// NewAuthenticationUPUDocumentAPIService creates a default api service
func NewAuthenticationUPUDocumentAPIService() AuthenticationUPUDocumentAPIServicer {
	return &AuthenticationUPUDocumentAPIService{}
}

// CreateAuthenticationUPU - To store the UPU acknowledgement information of a UE
func (s *AuthenticationUPUDocumentAPIService) CreateAuthenticationUPU(ctx context.Context, ueId string, upuData UpuData, supportedFeatures string) (ImplResponse, error) {
	// TODO - update CreateAuthenticationUPU with the required logic for this service method.
	// Add api_authentication_upu_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateAuthenticationUPU method not implemented")
}

// QueryAuthUPU - Retrieves the UPU acknowledgement information of a UE
func (s *AuthenticationUPUDocumentAPIService) QueryAuthUPU(ctx context.Context, ueId string, supportedFeatures string) (ImplResponse, error) {
	// TODO - update QueryAuthUPU with the required logic for this service method.
	// Add api_authentication_upu_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UpuData{}) or use other options such as http.Ok ...
	// return Response(200, UpuData{}), nil

	// TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	// return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryAuthUPU method not implemented")
}
