/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BdtDataPatch - Contains the modified background data transfer data.
type BdtDataPatch struct {
	TransPolicy TransferPolicy `json:"transPolicy,omitempty"`

	BdtpStatus BdtPolicyStatus `json:"bdtpStatus,omitempty"`
}

// AssertBdtDataPatchRequired checks if the required fields are not zero-ed
func AssertBdtDataPatchRequired(obj BdtDataPatch) error {
	if err := AssertTransferPolicyRequired(obj.TransPolicy); err != nil {
		return err
	}
	if err := AssertBdtPolicyStatusRequired(obj.BdtpStatus); err != nil {
		return err
	}
	return nil
}

// AssertBdtDataPatchConstraints checks if the values respects the defined constraints
func AssertBdtDataPatchConstraints(obj BdtDataPatch) error {
	return nil
}
