/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// WirelineServiceAreaRestriction1 - The \"restrictionType\" attribute and the \"areas\" attribute shall be either both present or absent.  The empty array of areas is used when service is allowed/restricted nowhere.
type WirelineServiceAreaRestriction1 struct {
	RestrictionType RestrictionType `json:"restrictionType,omitempty"`

	Areas []WirelineArea1 `json:"areas,omitempty"`
}

// AssertWirelineServiceAreaRestriction1Required checks if the required fields are not zero-ed
func AssertWirelineServiceAreaRestriction1Required(obj WirelineServiceAreaRestriction1) error {
	if err := AssertRestrictionTypeRequired(obj.RestrictionType); err != nil {
		return err
	}
	for _, el := range obj.Areas {
		if err := AssertWirelineArea1Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertWirelineServiceAreaRestriction1Constraints checks if the values respects the defined constraints
func AssertWirelineServiceAreaRestriction1Constraints(obj WirelineServiceAreaRestriction1) error {
	return nil
}
