/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NetworkNodeDiameterAddress struct {

	// Fully Qualified Domain Name
	Name string `json:"name"`

	// Fully Qualified Domain Name
	Realm string `json:"realm"`
}

// AssertNetworkNodeDiameterAddressRequired checks if the required fields are not zero-ed
func AssertNetworkNodeDiameterAddressRequired(obj NetworkNodeDiameterAddress) error {
	elements := map[string]interface{}{
		"name":  obj.Name,
		"realm": obj.Realm,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertNetworkNodeDiameterAddressConstraints checks if the values respects the defined constraints
func AssertNetworkNodeDiameterAddressConstraints(obj NetworkNodeDiameterAddress) error {
	return nil
}
