/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PfdChangeNotification - Represents information related to a notification of PFD change.
type PfdChangeNotification struct {

	// String providing an application identifier.
	ApplicationId string `json:"applicationId"`

	// Indication of removal of PFDs for an existing application identifier. Set to true indicates the PFDs are removed. Set to false indicates the PFDs are not removed. Default value is false if omitted.
	RemovalFlag bool `json:"removalFlag,omitempty"`

	// Indication of partial update of PFDs for an existing application identifier  if this operation is supported according to feature negotiation. Set to true indicates partial update PFDs for the included application identifier. Set to false indicates not partial update PFDs for the included application identifier. Default value is \"false\" if omitted.
	PartialFlag bool `json:"partialFlag,omitempty"`

	Pfds []PfdContent `json:"pfds,omitempty"`
}

// AssertPfdChangeNotificationRequired checks if the required fields are not zero-ed
func AssertPfdChangeNotificationRequired(obj PfdChangeNotification) error {
	elements := map[string]interface{}{
		"applicationId": obj.ApplicationId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Pfds {
		if err := AssertPfdContentRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPfdChangeNotificationConstraints checks if the values respects the defined constraints
func AssertPfdChangeNotificationConstraints(obj PfdChangeNotification) error {
	return nil
}
