/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// StationaryIndication - Possible values are: - STATIONARY: Identifies the UE is stationary - MOBILE: Identifies the UE is mobile
type StationaryIndication struct {
}

// AssertStationaryIndicationRequired checks if the required fields are not zero-ed
func AssertStationaryIndicationRequired(obj StationaryIndication) error {
	return nil
}

// AssertStationaryIndicationConstraints checks if the values respects the defined constraints
func AssertStationaryIndicationConstraints(obj StationaryIndication) error {
	return nil
}
