/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DataChangeNotify - Container for data which have changed and notification was requested when changed.
type DataChangeNotify struct {
	OriginalCallbackReference []string `json:"originalCallbackReference,omitempty"`

	// String represents the SUPI or GPSI
	UeId string `json:"ueId,omitempty"`

	NotifyItems []NotifyItem `json:"notifyItems,omitempty"`

	SdmSubscription SdmSubscription1 `json:"sdmSubscription,omitempty"`

	AdditionalSdmSubscriptions []SdmSubscription1 `json:"additionalSdmSubscriptions,omitempty"`

	SubscriptionDataSubscriptions []SubscriptionDataSubscriptions `json:"subscriptionDataSubscriptions,omitempty"`
}

// AssertDataChangeNotifyRequired checks if the required fields are not zero-ed
func AssertDataChangeNotifyRequired(obj DataChangeNotify) error {
	for _, el := range obj.NotifyItems {
		if err := AssertNotifyItemRequired(el); err != nil {
			return err
		}
	}
	if err := AssertSdmSubscription1Required(obj.SdmSubscription); err != nil {
		return err
	}
	for _, el := range obj.AdditionalSdmSubscriptions {
		if err := AssertSdmSubscription1Required(el); err != nil {
			return err
		}
	}
	for _, el := range obj.SubscriptionDataSubscriptions {
		if err := AssertSubscriptionDataSubscriptionsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDataChangeNotifyConstraints checks if the values respects the defined constraints
func AssertDataChangeNotifyConstraints(obj DataChangeNotify) error {
	return nil
}
