/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EventReportMode struct {
}

// AssertEventReportModeRequired checks if the required fields are not zero-ed
func AssertEventReportModeRequired(obj EventReportMode) error {
	return nil
}

// AssertEventReportModeConstraints checks if the values respects the defined constraints
func AssertEventReportModeConstraints(obj EventReportMode) error {
	return nil
}
