/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmPolicyDataPatch - Contains the SM policy data for a given subscriber.
type SmPolicyDataPatch struct {

	// Contains the remaining allowed usage data associated with the subscriber. The value of the limit identifier is used as the key of the map.
	UmData *map[string]UsageMonData `json:"umData,omitempty"`

	// Modifiable Session Management Policy data per S-NSSAI for all the SNSSAIs of the subscriber. The key of the map is the S-NSSAI.
	SmPolicySnssaiData map[string]SmPolicySnssaiDataPatch `json:"smPolicySnssaiData,omitempty"`
}

// AssertSmPolicyDataPatchRequired checks if the required fields are not zero-ed
func AssertSmPolicyDataPatchRequired(obj SmPolicyDataPatch) error {
	return nil
}

// AssertSmPolicyDataPatchConstraints checks if the values respects the defined constraints
func AssertSmPolicyDataPatchConstraints(obj SmPolicyDataPatch) error {
	return nil
}
