/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// BdtData - Contains the background data transfer data.
type BdtData struct {
	AspId string `json:"aspId"`

	TransPolicy TransferPolicy `json:"transPolicy"`

	// string identifying a BDT Reference ID as defined in clause 5.3.3 of 3GPP TS 29.154.
	BdtRefId string `json:"bdtRefId,omitempty"`

	NwAreaInfo NetworkAreaInfo2 `json:"nwAreaInfo,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NumOfUes int32 `json:"numOfUes,omitempty"`

	VolPerUe UsageThreshold `json:"volPerUe,omitempty"`

	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").
	Dnn string `json:"dnn,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`

	// Identify a traffic descriptor as defined in Figure 5.2.2 of 3GPP TS 24.526, octets v+5 to w.
	TrafficDes string `json:"trafficDes,omitempty"`

	BdtpStatus BdtPolicyStatus `json:"bdtpStatus,omitempty"`

	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SuppFeat string `json:"suppFeat,omitempty"`

	ResetIds []string `json:"resetIds,omitempty"`
}

// AssertBdtDataRequired checks if the required fields are not zero-ed
func AssertBdtDataRequired(obj BdtData) error {
	elements := map[string]interface{}{
		"aspId":       obj.AspId,
		"transPolicy": obj.TransPolicy,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTransferPolicyRequired(obj.TransPolicy); err != nil {
		return err
	}
	if err := AssertNetworkAreaInfo2Required(obj.NwAreaInfo); err != nil {
		return err
	}
	if err := AssertUsageThresholdRequired(obj.VolPerUe); err != nil {
		return err
	}
	if err := AssertSnssaiRequired(obj.Snssai); err != nil {
		return err
	}
	if err := AssertBdtPolicyStatusRequired(obj.BdtpStatus); err != nil {
		return err
	}
	return nil
}

// AssertBdtDataConstraints checks if the values respects the defined constraints
func AssertBdtDataConstraints(obj BdtData) error {
	if obj.NumOfUes < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
