/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmscData - Addresses of SM-Service Center entities with SMS wating to be delivered to the UE.
type SmscData struct {
	SmscMapAddress string `json:"smscMapAddress,omitempty"`

	SmscDiameterAddress NetworkNodeDiameterAddress1 `json:"smscDiameterAddress,omitempty"`
}

// AssertSmscDataRequired checks if the required fields are not zero-ed
func AssertSmscDataRequired(obj SmscData) error {
	if err := AssertNetworkNodeDiameterAddress1Required(obj.SmscDiameterAddress); err != nil {
		return err
	}
	return nil
}

// AssertSmscDataConstraints checks if the values respects the defined constraints
func AssertSmscDataConstraints(obj SmscData) error {
	return nil
}
