/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CellGlobalId - Contains a Cell Global Identification as defined in 3GPP TS 23.003, clause 4.3.1.
type CellGlobalId struct {
	PlmnId PlmnId1 `json:"plmnId"`

	Lac string `json:"lac"`

	CellId string `json:"cellId"`
}

// AssertCellGlobalIdRequired checks if the required fields are not zero-ed
func AssertCellGlobalIdRequired(obj CellGlobalId) error {
	elements := map[string]interface{}{
		"plmnId": obj.PlmnId,
		"lac":    obj.Lac,
		"cellId": obj.CellId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPlmnId1Required(obj.PlmnId); err != nil {
		return err
	}
	return nil
}

// AssertCellGlobalIdConstraints checks if the values respects the defined constraints
func AssertCellGlobalIdConstraints(obj CellGlobalId) error {
	return nil
}
