/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EcRestriction struct {
	AfInstanceId string `json:"afInstanceId"`

	ReferenceId int32 `json:"referenceId"`

	PlmnEcInfos []PlmnEcInfo `json:"plmnEcInfos,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`
}

// AssertEcRestrictionRequired checks if the required fields are not zero-ed
func AssertEcRestrictionRequired(obj EcRestriction) error {
	elements := map[string]interface{}{
		"afInstanceId": obj.AfInstanceId,
		"referenceId":  obj.ReferenceId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.PlmnEcInfos {
		if err := AssertPlmnEcInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEcRestrictionConstraints checks if the values respects the defined constraints
func AssertEcRestrictionConstraints(obj EcRestriction) error {
	return nil
}
