/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UeReachability - Describes the reachability of the UE
type UeReachability struct {
}

// AssertUeReachabilityRequired checks if the required fields are not zero-ed
func AssertUeReachabilityRequired(obj UeReachability) error {
	return nil
}

// AssertUeReachabilityConstraints checks if the values respects the defined constraints
func AssertUeReachabilityConstraints(obj UeReachability) error {
	return nil
}
