/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ImsVoPs struct {
}

// AssertImsVoPsRequired checks if the required fields are not zero-ed
func AssertImsVoPsRequired(obj ImsVoPs) error {
	return nil
}

// AssertImsVoPsConstraints checks if the values respects the defined constraints
func AssertImsVoPsConstraints(obj ImsVoPs) error {
	return nil
}
