/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AmfSubscriptionInfo - Information the UDR stores and retrieves related to active subscriptions at the AMF(s).
type AmfSubscriptionInfo struct {

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	AmfInstanceId string `json:"amfInstanceId"`

	// String providing an URI formatted according to RFC 3986.
	SubscriptionId string `json:"subscriptionId"`

	SubsChangeNotifyCorrelationId string `json:"subsChangeNotifyCorrelationId,omitempty"`

	ContextInfo ContextInfo `json:"contextInfo,omitempty"`
}

// AssertAmfSubscriptionInfoRequired checks if the required fields are not zero-ed
func AssertAmfSubscriptionInfoRequired(obj AmfSubscriptionInfo) error {
	elements := map[string]interface{}{
		"amfInstanceId":  obj.AmfInstanceId,
		"subscriptionId": obj.SubscriptionId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertContextInfoRequired(obj.ContextInfo); err != nil {
		return err
	}
	return nil
}

// AssertAmfSubscriptionInfoConstraints checks if the values respects the defined constraints
func AssertAmfSubscriptionInfoConstraints(obj AmfSubscriptionInfo) error {
	return nil
}
