/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SharedData struct {
	SharedDataId string `json:"sharedDataId"`

	SharedAmData AccessAndMobilitySubscriptionData1 `json:"sharedAmData,omitempty"`

	SharedSmsSubsData SmsSubscriptionData1 `json:"sharedSmsSubsData,omitempty"`

	SharedSmsMngSubsData SmsManagementSubscriptionData1 `json:"sharedSmsMngSubsData,omitempty"`

	// A map(list of key-value pairs) where Dnn, or optionally the Wildcard DNN, serves as key of DnnConfiguration
	SharedDnnConfigurations map[string]DnnConfiguration1 `json:"sharedDnnConfigurations,omitempty"`

	SharedTraceData *TraceData `json:"sharedTraceData,omitempty"`

	// A map(list of key-value pairs) where singleNssai serves as key of SnssaiInfo
	SharedSnssaiInfos map[string]SnssaiInfo `json:"sharedSnssaiInfos,omitempty"`

	// A map(list of key-value pairs) where GroupId serves as key of VnGroupData
	SharedVnGroupDatas map[string]VnGroupData `json:"sharedVnGroupDatas,omitempty"`

	// A map(list of key-value pairs) where JSON pointer pointing to an attribute within the SharedData serves as key of SharedDataTreatmentInstruction
	TreatmentInstructions map[string]SharedDataTreatmentInstruction `json:"treatmentInstructions,omitempty"`

	SharedSmSubsData SessionManagementSubscriptionData1 `json:"sharedSmSubsData,omitempty"`

	SharedEcsAddrConfigInfo *EcsAddrConfigInfo1 `json:"sharedEcsAddrConfigInfo,omitempty"`
}

// AssertSharedDataRequired checks if the required fields are not zero-ed
func AssertSharedDataRequired(obj SharedData) error {
	elements := map[string]interface{}{
		"sharedDataId": obj.SharedDataId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAccessAndMobilitySubscriptionData1Required(obj.SharedAmData); err != nil {
		return err
	}
	if err := AssertSmsSubscriptionData1Required(obj.SharedSmsSubsData); err != nil {
		return err
	}
	if err := AssertSmsManagementSubscriptionData1Required(obj.SharedSmsMngSubsData); err != nil {
		return err
	}
	if obj.SharedTraceData != nil {
		if err := AssertTraceDataRequired(*obj.SharedTraceData); err != nil {
			return err
		}
	}
	if err := AssertSessionManagementSubscriptionData1Required(obj.SharedSmSubsData); err != nil {
		return err
	}
	if obj.SharedEcsAddrConfigInfo != nil {
		if err := AssertEcsAddrConfigInfo1Required(*obj.SharedEcsAddrConfigInfo); err != nil {
			return err
		}
	}
	return nil
}

// AssertSharedDataConstraints checks if the values respects the defined constraints
func AssertSharedDataConstraints(obj SharedData) error {
	return nil
}
