/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AmInfluEvent - Represents the service area coverage outcome event.
type AmInfluEvent struct {
}

// AssertAmInfluEventRequired checks if the required fields are not zero-ed
func AssertAmInfluEventRequired(obj AmInfluEvent) error {
	return nil
}

// AssertAmInfluEventConstraints checks if the values respects the defined constraints
func AssertAmInfluEventConstraints(obj AmInfluEvent) error {
	return nil
}
