/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UePolicySection - Contains the UE policy section.
type UePolicySection struct {

	// string with format 'bytes' as defined in OpenAPI
	UePolicySectionInfo string `json:"uePolicySectionInfo"`

	Upsi string `json:"upsi"`
}

// AssertUePolicySectionRequired checks if the required fields are not zero-ed
func AssertUePolicySectionRequired(obj UePolicySection) error {
	elements := map[string]interface{}{
		"uePolicySectionInfo": obj.UePolicySectionInfo,
		"upsi":                obj.Upsi,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUePolicySectionConstraints checks if the values respects the defined constraints
func AssertUePolicySectionConstraints(obj UePolicySection) error {
	return nil
}
