/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// CagAckData - Used to store the status of the latest CAG data update.
type CagAckData struct {

	// string with format 'date-time' as defined in OpenAPI.
	ProvisioningTime time.Time `json:"provisioningTime"`

	UeUpdateStatus UeUpdateStatus `json:"ueUpdateStatus"`
}

// AssertCagAckDataRequired checks if the required fields are not zero-ed
func AssertCagAckDataRequired(obj CagAckData) error {
	elements := map[string]interface{}{
		"provisioningTime": obj.ProvisioningTime,
		"ueUpdateStatus":   obj.UeUpdateStatus,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCagAckDataConstraints checks if the values respects the defined constraints
func AssertCagAckDataConstraints(obj CagAckData) error {
	return nil
}
