/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdditionalEeSubsInfo struct {
	AmfSubscriptionInfoList []AmfSubscriptionInfo `json:"amfSubscriptionInfoList,omitempty"`

	SmfSubscriptionInfo SmfSubscriptionInfo `json:"smfSubscriptionInfo,omitempty"`

	HssSubscriptionInfo HssSubscriptionInfo `json:"hssSubscriptionInfo,omitempty"`
}

// AssertAdditionalEeSubsInfoRequired checks if the required fields are not zero-ed
func AssertAdditionalEeSubsInfoRequired(obj AdditionalEeSubsInfo) error {
	for _, el := range obj.AmfSubscriptionInfoList {
		if err := AssertAmfSubscriptionInfoRequired(el); err != nil {
			return err
		}
	}
	if err := AssertSmfSubscriptionInfoRequired(obj.SmfSubscriptionInfo); err != nil {
		return err
	}
	if err := AssertHssSubscriptionInfoRequired(obj.HssSubscriptionInfo); err != nil {
		return err
	}
	return nil
}

// AssertAdditionalEeSubsInfoConstraints checks if the values respects the defined constraints
func AssertAdditionalEeSubsInfoConstraints(obj AdditionalEeSubsInfo) error {
	return nil
}
