/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// UsageMonDataLimit - Contains usage monitoring control data for a subscriber.
type UsageMonDataLimit struct {
	LimitId string `json:"limitId"`

	// Identifies the SNSSAI and DNN combinations to which the usage monitoring data limit applies. The S-NSSAI is the key of the map.
	Scopes map[string]UsageMonDataScope `json:"scopes,omitempty"`

	UmLevel UsageMonLevel `json:"umLevel,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	StartDate time.Time `json:"startDate,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	EndDate time.Time `json:"endDate,omitempty"`

	UsageLimit UsageThreshold `json:"usageLimit,omitempty"`

	ResetPeriod TimePeriod `json:"resetPeriod,omitempty"`
}

// AssertUsageMonDataLimitRequired checks if the required fields are not zero-ed
func AssertUsageMonDataLimitRequired(obj UsageMonDataLimit) error {
	elements := map[string]interface{}{
		"limitId": obj.LimitId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUsageMonLevelRequired(obj.UmLevel); err != nil {
		return err
	}
	if err := AssertUsageThresholdRequired(obj.UsageLimit); err != nil {
		return err
	}
	if err := AssertTimePeriodRequired(obj.ResetPeriod); err != nil {
		return err
	}
	return nil
}

// AssertUsageMonDataLimitConstraints checks if the values respects the defined constraints
func AssertUsageMonDataLimitConstraints(obj UsageMonDataLimit) error {
	return nil
}
