/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// HssSubscriptionInfo - Information related to active subscriptions at the HSS(s)
type HssSubscriptionInfo struct {
	HssSubscriptionList []HssSubscriptionItem `json:"hssSubscriptionList"`
}

// AssertHssSubscriptionInfoRequired checks if the required fields are not zero-ed
func AssertHssSubscriptionInfoRequired(obj HssSubscriptionInfo) error {
	elements := map[string]interface{}{
		"hssSubscriptionList": obj.HssSubscriptionList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.HssSubscriptionList {
		if err := AssertHssSubscriptionItemRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertHssSubscriptionInfoConstraints checks if the values respects the defined constraints
func AssertHssSubscriptionInfoConstraints(obj HssSubscriptionInfo) error {
	return nil
}
