/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BackupAmfInfo - Provides details of the Backup AMF.
type BackupAmfInfo struct {

	// Fully Qualified Domain Name
	BackupAmf string `json:"backupAmf"`

	// If present, this IE shall contain the list of GUAMI(s) (supported by the AMF) for which the backupAmf IE applies.
	GuamiList []Guami `json:"guamiList,omitempty"`
}

// AssertBackupAmfInfoRequired checks if the required fields are not zero-ed
func AssertBackupAmfInfoRequired(obj BackupAmfInfo) error {
	elements := map[string]interface{}{
		"backupAmf": obj.BackupAmf,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.GuamiList {
		if err := AssertGuamiRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBackupAmfInfoConstraints checks if the values respects the defined constraints
func AssertBackupAmfInfoConstraints(obj BackupAmfInfo) error {
	return nil
}
