/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SpatialValidityCond1 - Contains the Spatial Validity Condition.
type SpatialValidityCond1 struct {
	TrackingAreaList []Tai1 `json:"trackingAreaList,omitempty"`

	Countries []string `json:"countries,omitempty"`

	GeographicalServiceArea GeoServiceArea1 `json:"geographicalServiceArea,omitempty"`
}

// AssertSpatialValidityCond1Required checks if the required fields are not zero-ed
func AssertSpatialValidityCond1Required(obj SpatialValidityCond1) error {
	for _, el := range obj.TrackingAreaList {
		if err := AssertTai1Required(el); err != nil {
			return err
		}
	}
	if err := AssertGeoServiceArea1Required(obj.GeographicalServiceArea); err != nil {
		return err
	}
	return nil
}

// AssertSpatialValidityCond1Constraints checks if the values respects the defined constraints
func AssertSpatialValidityCond1Constraints(obj SpatialValidityCond1) error {
	return nil
}
