/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmsSupport - Indicates the supported SMS delivery of a UE
type SmsSupport struct {
}

// AssertSmsSupportRequired checks if the required fields are not zero-ed
func AssertSmsSupportRequired(obj SmsSupport) error {
	return nil
}

// AssertSmsSupportConstraints checks if the values respects the defined constraints
func AssertSmsSupportConstraints(obj SmsSupport) error {
	return nil
}
