/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PolicyDataChangeNotification - Contains changed policy data for which notification was requested.
type PolicyDataChangeNotification struct {
	AmPolicyData AmPolicyData `json:"amPolicyData,omitempty"`

	UePolicySet UePolicySet `json:"uePolicySet,omitempty"`

	PlmnUePolicySet UePolicySet `json:"plmnUePolicySet,omitempty"`

	SmPolicyData SmPolicyData `json:"smPolicyData,omitempty"`

	UsageMonData UsageMonData `json:"usageMonData,omitempty"`

	SponsorConnectivityData SponsorConnectivityData `json:"SponsorConnectivityData,omitempty"`

	BdtData BdtData `json:"bdtData,omitempty"`

	OpSpecData OperatorSpecificDataContainer `json:"opSpecData,omitempty"`

	// Operator Specific Data resource data, if changed and notification was requested. The key of the map is operator specific data element name and the value is the operator specific data of the UE.
	OpSpecDataMap map[string]OperatorSpecificDataContainer `json:"opSpecDataMap,omitempty"`

	// String represents the SUPI or GPSI
	UeId string `json:"ueId,omitempty"`

	SponsorId string `json:"sponsorId,omitempty"`

	// string identifying a BDT Reference ID as defined in clause 5.3.3 of 3GPP TS 29.154.
	BdtRefId string `json:"bdtRefId,omitempty"`

	UsageMonId string `json:"usageMonId,omitempty"`

	PlmnId PlmnId1 `json:"plmnId,omitempty"`

	DelResources []string `json:"delResources,omitempty"`

	NotifId string `json:"notifId,omitempty"`

	ReportedFragments []NotificationItem `json:"reportedFragments,omitempty"`

	SlicePolicyData SlicePolicyData `json:"slicePolicyData,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`
}

// AssertPolicyDataChangeNotificationRequired checks if the required fields are not zero-ed
func AssertPolicyDataChangeNotificationRequired(obj PolicyDataChangeNotification) error {
	if err := AssertAmPolicyDataRequired(obj.AmPolicyData); err != nil {
		return err
	}
	if err := AssertUePolicySetRequired(obj.UePolicySet); err != nil {
		return err
	}
	if err := AssertUePolicySetRequired(obj.PlmnUePolicySet); err != nil {
		return err
	}
	if err := AssertSmPolicyDataRequired(obj.SmPolicyData); err != nil {
		return err
	}
	if err := AssertUsageMonDataRequired(obj.UsageMonData); err != nil {
		return err
	}
	if err := AssertSponsorConnectivityDataRequired(obj.SponsorConnectivityData); err != nil {
		return err
	}
	if err := AssertBdtDataRequired(obj.BdtData); err != nil {
		return err
	}
	if err := AssertOperatorSpecificDataContainerRequired(obj.OpSpecData); err != nil {
		return err
	}
	if err := AssertPlmnId1Required(obj.PlmnId); err != nil {
		return err
	}
	for _, el := range obj.ReportedFragments {
		if err := AssertNotificationItemRequired(el); err != nil {
			return err
		}
	}
	if err := AssertSlicePolicyDataRequired(obj.SlicePolicyData); err != nil {
		return err
	}
	if err := AssertSnssaiRequired(obj.Snssai); err != nil {
		return err
	}
	return nil
}

// AssertPolicyDataChangeNotificationConstraints checks if the values respects the defined constraints
func AssertPolicyDataChangeNotificationConstraints(obj PolicyDataChangeNotification) error {
	return nil
}
