/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type PpSubsRegTimer struct {

	// indicating a time in seconds.
	SubsRegTimer int32 `json:"subsRegTimer"`

	AfInstanceId string `json:"afInstanceId"`

	ReferenceId int32 `json:"referenceId"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`
}

// AssertPpSubsRegTimerRequired checks if the required fields are not zero-ed
func AssertPpSubsRegTimerRequired(obj PpSubsRegTimer) error {
	elements := map[string]interface{}{
		"subsRegTimer": obj.SubsRegTimer,
		"afInstanceId": obj.AfInstanceId,
		"referenceId":  obj.ReferenceId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPpSubsRegTimerConstraints checks if the values respects the defined constraints
func AssertPpSubsRegTimerConstraints(obj PpSubsRegTimer) error {
	return nil
}
