/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the QosData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QosData{}

// QosData struct for QosData
type QosData struct {
	// Univocally identifies the QoS control policy data within a PDU session.
	QosId string `json:"qosId"`
	Var5qi *int32 `json:"5qi,omitempty"`
	MaxbrUl NullableString `json:"maxbrUl,omitempty"`
	MaxbrDl NullableString `json:"maxbrDl,omitempty"`
	GbrUl NullableString `json:"gbrUl,omitempty"`
	GbrDl NullableString `json:"gbrDl,omitempty"`
	Arp *Arp `json:"arp,omitempty"`
	// Indicates whether notifications are requested from 3GPP NG-RAN when the GFBR can no longer (or again) be guaranteed for a QoS Flow during the lifetime of the QoS Flow.
	Qnc *bool `json:"qnc,omitempty"`
	PriorityLevel NullableInt32 `json:"priorityLevel,omitempty"`
	AverWindow NullableInt32 `json:"averWindow,omitempty"`
	MaxDataBurstVol NullableInt32 `json:"maxDataBurstVol,omitempty"`
	// Indicates whether the QoS information is reflective for the corresponding service data flow.
	ReflectiveQos *bool `json:"reflectiveQos,omitempty"`
	// Indicates, by containing the same value, what PCC rules may share resource in downlink direction.
	SharingKeyDl *string `json:"sharingKeyDl,omitempty"`
	// Indicates, by containing the same value, what PCC rules may share resource in uplink direction.
	SharingKeyUl *string `json:"sharingKeyUl,omitempty"`
	MaxPacketLossRateDl NullableInt32 `json:"maxPacketLossRateDl,omitempty"`
	MaxPacketLossRateUl NullableInt32 `json:"maxPacketLossRateUl,omitempty"`
	// Indicates that the dynamic PCC rule shall always have its binding with the QoS Flow associated with the default QoS rule
	DefQosFlowIndication *bool `json:"defQosFlowIndication,omitempty"`
}

type _QosData QosData

// NewQosData instantiates a new QosData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQosData(qosId string) *QosData {
	this := QosData{}
	this.QosId = qosId
	var averWindow int32 = 2000
	this.AverWindow = *NewNullableInt32(&averWindow)
	return &this
}

// NewQosDataWithDefaults instantiates a new QosData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQosDataWithDefaults() *QosData {
	this := QosData{}
	var averWindow int32 = 2000
	this.AverWindow = *NewNullableInt32(&averWindow)
	return &this
}

// GetQosId returns the QosId field value
func (o *QosData) GetQosId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QosId
}

// GetQosIdOk returns a tuple with the QosId field value
// and a boolean to check if the value has been set.
func (o *QosData) GetQosIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QosId, true
}

// SetQosId sets field value
func (o *QosData) SetQosId(v string) {
	o.QosId = v
}

// GetVar5qi returns the Var5qi field value if set, zero value otherwise.
func (o *QosData) GetVar5qi() int32 {
	if o == nil || IsNil(o.Var5qi) {
		var ret int32
		return ret
	}
	return *o.Var5qi
}

// GetVar5qiOk returns a tuple with the Var5qi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetVar5qiOk() (*int32, bool) {
	if o == nil || IsNil(o.Var5qi) {
		return nil, false
	}
	return o.Var5qi, true
}

// HasVar5qi returns a boolean if a field has been set.
func (o *QosData) HasVar5qi() bool {
	if o != nil && !IsNil(o.Var5qi) {
		return true
	}

	return false
}

// SetVar5qi gets a reference to the given int32 and assigns it to the Var5qi field.
func (o *QosData) SetVar5qi(v int32) {
	o.Var5qi = &v
}

// GetMaxbrUl returns the MaxbrUl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetMaxbrUl() string {
	if o == nil || IsNil(o.MaxbrUl.Get()) {
		var ret string
		return ret
	}
	return *o.MaxbrUl.Get()
}

// GetMaxbrUlOk returns a tuple with the MaxbrUl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetMaxbrUlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxbrUl.Get(), o.MaxbrUl.IsSet()
}

// HasMaxbrUl returns a boolean if a field has been set.
func (o *QosData) HasMaxbrUl() bool {
	if o != nil && o.MaxbrUl.IsSet() {
		return true
	}

	return false
}

// SetMaxbrUl gets a reference to the given NullableString and assigns it to the MaxbrUl field.
func (o *QosData) SetMaxbrUl(v string) {
	o.MaxbrUl.Set(&v)
}
// SetMaxbrUlNil sets the value for MaxbrUl to be an explicit nil
func (o *QosData) SetMaxbrUlNil() {
	o.MaxbrUl.Set(nil)
}

// UnsetMaxbrUl ensures that no value is present for MaxbrUl, not even an explicit nil
func (o *QosData) UnsetMaxbrUl() {
	o.MaxbrUl.Unset()
}

// GetMaxbrDl returns the MaxbrDl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetMaxbrDl() string {
	if o == nil || IsNil(o.MaxbrDl.Get()) {
		var ret string
		return ret
	}
	return *o.MaxbrDl.Get()
}

// GetMaxbrDlOk returns a tuple with the MaxbrDl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetMaxbrDlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxbrDl.Get(), o.MaxbrDl.IsSet()
}

// HasMaxbrDl returns a boolean if a field has been set.
func (o *QosData) HasMaxbrDl() bool {
	if o != nil && o.MaxbrDl.IsSet() {
		return true
	}

	return false
}

// SetMaxbrDl gets a reference to the given NullableString and assigns it to the MaxbrDl field.
func (o *QosData) SetMaxbrDl(v string) {
	o.MaxbrDl.Set(&v)
}
// SetMaxbrDlNil sets the value for MaxbrDl to be an explicit nil
func (o *QosData) SetMaxbrDlNil() {
	o.MaxbrDl.Set(nil)
}

// UnsetMaxbrDl ensures that no value is present for MaxbrDl, not even an explicit nil
func (o *QosData) UnsetMaxbrDl() {
	o.MaxbrDl.Unset()
}

// GetGbrUl returns the GbrUl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetGbrUl() string {
	if o == nil || IsNil(o.GbrUl.Get()) {
		var ret string
		return ret
	}
	return *o.GbrUl.Get()
}

// GetGbrUlOk returns a tuple with the GbrUl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetGbrUlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GbrUl.Get(), o.GbrUl.IsSet()
}

// HasGbrUl returns a boolean if a field has been set.
func (o *QosData) HasGbrUl() bool {
	if o != nil && o.GbrUl.IsSet() {
		return true
	}

	return false
}

// SetGbrUl gets a reference to the given NullableString and assigns it to the GbrUl field.
func (o *QosData) SetGbrUl(v string) {
	o.GbrUl.Set(&v)
}
// SetGbrUlNil sets the value for GbrUl to be an explicit nil
func (o *QosData) SetGbrUlNil() {
	o.GbrUl.Set(nil)
}

// UnsetGbrUl ensures that no value is present for GbrUl, not even an explicit nil
func (o *QosData) UnsetGbrUl() {
	o.GbrUl.Unset()
}

// GetGbrDl returns the GbrDl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetGbrDl() string {
	if o == nil || IsNil(o.GbrDl.Get()) {
		var ret string
		return ret
	}
	return *o.GbrDl.Get()
}

// GetGbrDlOk returns a tuple with the GbrDl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetGbrDlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GbrDl.Get(), o.GbrDl.IsSet()
}

// HasGbrDl returns a boolean if a field has been set.
func (o *QosData) HasGbrDl() bool {
	if o != nil && o.GbrDl.IsSet() {
		return true
	}

	return false
}

// SetGbrDl gets a reference to the given NullableString and assigns it to the GbrDl field.
func (o *QosData) SetGbrDl(v string) {
	o.GbrDl.Set(&v)
}
// SetGbrDlNil sets the value for GbrDl to be an explicit nil
func (o *QosData) SetGbrDlNil() {
	o.GbrDl.Set(nil)
}

// UnsetGbrDl ensures that no value is present for GbrDl, not even an explicit nil
func (o *QosData) UnsetGbrDl() {
	o.GbrDl.Unset()
}

// GetArp returns the Arp field value if set, zero value otherwise.
func (o *QosData) GetArp() Arp {
	if o == nil || IsNil(o.Arp) {
		var ret Arp
		return ret
	}
	return *o.Arp
}

// GetArpOk returns a tuple with the Arp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetArpOk() (*Arp, bool) {
	if o == nil || IsNil(o.Arp) {
		return nil, false
	}
	return o.Arp, true
}

// HasArp returns a boolean if a field has been set.
func (o *QosData) HasArp() bool {
	if o != nil && !IsNil(o.Arp) {
		return true
	}

	return false
}

// SetArp gets a reference to the given Arp and assigns it to the Arp field.
func (o *QosData) SetArp(v Arp) {
	o.Arp = &v
}

// GetQnc returns the Qnc field value if set, zero value otherwise.
func (o *QosData) GetQnc() bool {
	if o == nil || IsNil(o.Qnc) {
		var ret bool
		return ret
	}
	return *o.Qnc
}

// GetQncOk returns a tuple with the Qnc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetQncOk() (*bool, bool) {
	if o == nil || IsNil(o.Qnc) {
		return nil, false
	}
	return o.Qnc, true
}

// HasQnc returns a boolean if a field has been set.
func (o *QosData) HasQnc() bool {
	if o != nil && !IsNil(o.Qnc) {
		return true
	}

	return false
}

// SetQnc gets a reference to the given bool and assigns it to the Qnc field.
func (o *QosData) SetQnc(v bool) {
	o.Qnc = &v
}

// GetPriorityLevel returns the PriorityLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetPriorityLevel() int32 {
	if o == nil || IsNil(o.PriorityLevel.Get()) {
		var ret int32
		return ret
	}
	return *o.PriorityLevel.Get()
}

// GetPriorityLevelOk returns a tuple with the PriorityLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetPriorityLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PriorityLevel.Get(), o.PriorityLevel.IsSet()
}

// HasPriorityLevel returns a boolean if a field has been set.
func (o *QosData) HasPriorityLevel() bool {
	if o != nil && o.PriorityLevel.IsSet() {
		return true
	}

	return false
}

// SetPriorityLevel gets a reference to the given NullableInt32 and assigns it to the PriorityLevel field.
func (o *QosData) SetPriorityLevel(v int32) {
	o.PriorityLevel.Set(&v)
}
// SetPriorityLevelNil sets the value for PriorityLevel to be an explicit nil
func (o *QosData) SetPriorityLevelNil() {
	o.PriorityLevel.Set(nil)
}

// UnsetPriorityLevel ensures that no value is present for PriorityLevel, not even an explicit nil
func (o *QosData) UnsetPriorityLevel() {
	o.PriorityLevel.Unset()
}

// GetAverWindow returns the AverWindow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetAverWindow() int32 {
	if o == nil || IsNil(o.AverWindow.Get()) {
		var ret int32
		return ret
	}
	return *o.AverWindow.Get()
}

// GetAverWindowOk returns a tuple with the AverWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetAverWindowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AverWindow.Get(), o.AverWindow.IsSet()
}

// HasAverWindow returns a boolean if a field has been set.
func (o *QosData) HasAverWindow() bool {
	if o != nil && o.AverWindow.IsSet() {
		return true
	}

	return false
}

// SetAverWindow gets a reference to the given NullableInt32 and assigns it to the AverWindow field.
func (o *QosData) SetAverWindow(v int32) {
	o.AverWindow.Set(&v)
}
// SetAverWindowNil sets the value for AverWindow to be an explicit nil
func (o *QosData) SetAverWindowNil() {
	o.AverWindow.Set(nil)
}

// UnsetAverWindow ensures that no value is present for AverWindow, not even an explicit nil
func (o *QosData) UnsetAverWindow() {
	o.AverWindow.Unset()
}

// GetMaxDataBurstVol returns the MaxDataBurstVol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetMaxDataBurstVol() int32 {
	if o == nil || IsNil(o.MaxDataBurstVol.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxDataBurstVol.Get()
}

// GetMaxDataBurstVolOk returns a tuple with the MaxDataBurstVol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetMaxDataBurstVolOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxDataBurstVol.Get(), o.MaxDataBurstVol.IsSet()
}

// HasMaxDataBurstVol returns a boolean if a field has been set.
func (o *QosData) HasMaxDataBurstVol() bool {
	if o != nil && o.MaxDataBurstVol.IsSet() {
		return true
	}

	return false
}

// SetMaxDataBurstVol gets a reference to the given NullableInt32 and assigns it to the MaxDataBurstVol field.
func (o *QosData) SetMaxDataBurstVol(v int32) {
	o.MaxDataBurstVol.Set(&v)
}
// SetMaxDataBurstVolNil sets the value for MaxDataBurstVol to be an explicit nil
func (o *QosData) SetMaxDataBurstVolNil() {
	o.MaxDataBurstVol.Set(nil)
}

// UnsetMaxDataBurstVol ensures that no value is present for MaxDataBurstVol, not even an explicit nil
func (o *QosData) UnsetMaxDataBurstVol() {
	o.MaxDataBurstVol.Unset()
}

// GetReflectiveQos returns the ReflectiveQos field value if set, zero value otherwise.
func (o *QosData) GetReflectiveQos() bool {
	if o == nil || IsNil(o.ReflectiveQos) {
		var ret bool
		return ret
	}
	return *o.ReflectiveQos
}

// GetReflectiveQosOk returns a tuple with the ReflectiveQos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetReflectiveQosOk() (*bool, bool) {
	if o == nil || IsNil(o.ReflectiveQos) {
		return nil, false
	}
	return o.ReflectiveQos, true
}

// HasReflectiveQos returns a boolean if a field has been set.
func (o *QosData) HasReflectiveQos() bool {
	if o != nil && !IsNil(o.ReflectiveQos) {
		return true
	}

	return false
}

// SetReflectiveQos gets a reference to the given bool and assigns it to the ReflectiveQos field.
func (o *QosData) SetReflectiveQos(v bool) {
	o.ReflectiveQos = &v
}

// GetSharingKeyDl returns the SharingKeyDl field value if set, zero value otherwise.
func (o *QosData) GetSharingKeyDl() string {
	if o == nil || IsNil(o.SharingKeyDl) {
		var ret string
		return ret
	}
	return *o.SharingKeyDl
}

// GetSharingKeyDlOk returns a tuple with the SharingKeyDl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetSharingKeyDlOk() (*string, bool) {
	if o == nil || IsNil(o.SharingKeyDl) {
		return nil, false
	}
	return o.SharingKeyDl, true
}

// HasSharingKeyDl returns a boolean if a field has been set.
func (o *QosData) HasSharingKeyDl() bool {
	if o != nil && !IsNil(o.SharingKeyDl) {
		return true
	}

	return false
}

// SetSharingKeyDl gets a reference to the given string and assigns it to the SharingKeyDl field.
func (o *QosData) SetSharingKeyDl(v string) {
	o.SharingKeyDl = &v
}

// GetSharingKeyUl returns the SharingKeyUl field value if set, zero value otherwise.
func (o *QosData) GetSharingKeyUl() string {
	if o == nil || IsNil(o.SharingKeyUl) {
		var ret string
		return ret
	}
	return *o.SharingKeyUl
}

// GetSharingKeyUlOk returns a tuple with the SharingKeyUl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetSharingKeyUlOk() (*string, bool) {
	if o == nil || IsNil(o.SharingKeyUl) {
		return nil, false
	}
	return o.SharingKeyUl, true
}

// HasSharingKeyUl returns a boolean if a field has been set.
func (o *QosData) HasSharingKeyUl() bool {
	if o != nil && !IsNil(o.SharingKeyUl) {
		return true
	}

	return false
}

// SetSharingKeyUl gets a reference to the given string and assigns it to the SharingKeyUl field.
func (o *QosData) SetSharingKeyUl(v string) {
	o.SharingKeyUl = &v
}

// GetMaxPacketLossRateDl returns the MaxPacketLossRateDl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetMaxPacketLossRateDl() int32 {
	if o == nil || IsNil(o.MaxPacketLossRateDl.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxPacketLossRateDl.Get()
}

// GetMaxPacketLossRateDlOk returns a tuple with the MaxPacketLossRateDl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetMaxPacketLossRateDlOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxPacketLossRateDl.Get(), o.MaxPacketLossRateDl.IsSet()
}

// HasMaxPacketLossRateDl returns a boolean if a field has been set.
func (o *QosData) HasMaxPacketLossRateDl() bool {
	if o != nil && o.MaxPacketLossRateDl.IsSet() {
		return true
	}

	return false
}

// SetMaxPacketLossRateDl gets a reference to the given NullableInt32 and assigns it to the MaxPacketLossRateDl field.
func (o *QosData) SetMaxPacketLossRateDl(v int32) {
	o.MaxPacketLossRateDl.Set(&v)
}
// SetMaxPacketLossRateDlNil sets the value for MaxPacketLossRateDl to be an explicit nil
func (o *QosData) SetMaxPacketLossRateDlNil() {
	o.MaxPacketLossRateDl.Set(nil)
}

// UnsetMaxPacketLossRateDl ensures that no value is present for MaxPacketLossRateDl, not even an explicit nil
func (o *QosData) UnsetMaxPacketLossRateDl() {
	o.MaxPacketLossRateDl.Unset()
}

// GetMaxPacketLossRateUl returns the MaxPacketLossRateUl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QosData) GetMaxPacketLossRateUl() int32 {
	if o == nil || IsNil(o.MaxPacketLossRateUl.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxPacketLossRateUl.Get()
}

// GetMaxPacketLossRateUlOk returns a tuple with the MaxPacketLossRateUl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QosData) GetMaxPacketLossRateUlOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxPacketLossRateUl.Get(), o.MaxPacketLossRateUl.IsSet()
}

// HasMaxPacketLossRateUl returns a boolean if a field has been set.
func (o *QosData) HasMaxPacketLossRateUl() bool {
	if o != nil && o.MaxPacketLossRateUl.IsSet() {
		return true
	}

	return false
}

// SetMaxPacketLossRateUl gets a reference to the given NullableInt32 and assigns it to the MaxPacketLossRateUl field.
func (o *QosData) SetMaxPacketLossRateUl(v int32) {
	o.MaxPacketLossRateUl.Set(&v)
}
// SetMaxPacketLossRateUlNil sets the value for MaxPacketLossRateUl to be an explicit nil
func (o *QosData) SetMaxPacketLossRateUlNil() {
	o.MaxPacketLossRateUl.Set(nil)
}

// UnsetMaxPacketLossRateUl ensures that no value is present for MaxPacketLossRateUl, not even an explicit nil
func (o *QosData) UnsetMaxPacketLossRateUl() {
	o.MaxPacketLossRateUl.Unset()
}

// GetDefQosFlowIndication returns the DefQosFlowIndication field value if set, zero value otherwise.
func (o *QosData) GetDefQosFlowIndication() bool {
	if o == nil || IsNil(o.DefQosFlowIndication) {
		var ret bool
		return ret
	}
	return *o.DefQosFlowIndication
}

// GetDefQosFlowIndicationOk returns a tuple with the DefQosFlowIndication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosData) GetDefQosFlowIndicationOk() (*bool, bool) {
	if o == nil || IsNil(o.DefQosFlowIndication) {
		return nil, false
	}
	return o.DefQosFlowIndication, true
}

// HasDefQosFlowIndication returns a boolean if a field has been set.
func (o *QosData) HasDefQosFlowIndication() bool {
	if o != nil && !IsNil(o.DefQosFlowIndication) {
		return true
	}

	return false
}

// SetDefQosFlowIndication gets a reference to the given bool and assigns it to the DefQosFlowIndication field.
func (o *QosData) SetDefQosFlowIndication(v bool) {
	o.DefQosFlowIndication = &v
}

func (o QosData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QosData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["qosId"] = o.QosId
	if !IsNil(o.Var5qi) {
		toSerialize["5qi"] = o.Var5qi
	}
	if o.MaxbrUl.IsSet() {
		toSerialize["maxbrUl"] = o.MaxbrUl.Get()
	}
	if o.MaxbrDl.IsSet() {
		toSerialize["maxbrDl"] = o.MaxbrDl.Get()
	}
	if o.GbrUl.IsSet() {
		toSerialize["gbrUl"] = o.GbrUl.Get()
	}
	if o.GbrDl.IsSet() {
		toSerialize["gbrDl"] = o.GbrDl.Get()
	}
	if !IsNil(o.Arp) {
		toSerialize["arp"] = o.Arp
	}
	if !IsNil(o.Qnc) {
		toSerialize["qnc"] = o.Qnc
	}
	if o.PriorityLevel.IsSet() {
		toSerialize["priorityLevel"] = o.PriorityLevel.Get()
	}
	if o.AverWindow.IsSet() {
		toSerialize["averWindow"] = o.AverWindow.Get()
	}
	if o.MaxDataBurstVol.IsSet() {
		toSerialize["maxDataBurstVol"] = o.MaxDataBurstVol.Get()
	}
	if !IsNil(o.ReflectiveQos) {
		toSerialize["reflectiveQos"] = o.ReflectiveQos
	}
	if !IsNil(o.SharingKeyDl) {
		toSerialize["sharingKeyDl"] = o.SharingKeyDl
	}
	if !IsNil(o.SharingKeyUl) {
		toSerialize["sharingKeyUl"] = o.SharingKeyUl
	}
	if o.MaxPacketLossRateDl.IsSet() {
		toSerialize["maxPacketLossRateDl"] = o.MaxPacketLossRateDl.Get()
	}
	if o.MaxPacketLossRateUl.IsSet() {
		toSerialize["maxPacketLossRateUl"] = o.MaxPacketLossRateUl.Get()
	}
	if !IsNil(o.DefQosFlowIndication) {
		toSerialize["defQosFlowIndication"] = o.DefQosFlowIndication
	}
	return toSerialize, nil
}

func (o *QosData) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"qosId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQosData := _QosData{}

	err = json.Unmarshal(bytes, &varQosData)

	if err != nil {
		return err
	}

	*o = QosData(varQosData)

	return err
}

type NullableQosData struct {
	value *QosData
	isSet bool
}

func (v NullableQosData) Get() *QosData {
	return v.value
}

func (v *NullableQosData) Set(val *QosData) {
	v.value = val
	v.isSet = true
}

func (v NullableQosData) IsSet() bool {
	return v.isSet
}

func (v *NullableQosData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQosData(val *QosData) *NullableQosData {
	return &NullableQosData{value: val, isSet: true}
}

func (v NullableQosData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQosData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


