/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

import (
	"errors"
	"time"
)

type UsageMonitoringData struct {

	// Univocally identifies the usage monitoring policy data within a PDU session.
	UmId string `json:"umId"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	VolumeThreshold *int64 `json:"volumeThreshold,omitempty"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	VolumeThresholdUplink *int64 `json:"volumeThresholdUplink,omitempty"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	VolumeThresholdDownlink *int64 `json:"volumeThresholdDownlink,omitempty"`

	TimeThreshold *int32 `json:"timeThreshold,omitempty"`

	MonitoringTime *time.Time `json:"monitoringTime,omitempty"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	NextVolThreshold *int64 `json:"nextVolThreshold,omitempty"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	NextVolThresholdUplink *int64 `json:"nextVolThresholdUplink,omitempty"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	NextVolThresholdDownlink *int64 `json:"nextVolThresholdDownlink,omitempty"`

	NextTimeThreshold *int32 `json:"nextTimeThreshold,omitempty"`

	InactivityTime *int32 `json:"inactivityTime,omitempty"`

	// Contains the PCC rule identifier(s) which corresponding service data flow(s) shall be excluded from PDU Session usage monitoring. It is only included in the UsageMonitoringData instance for session level usage monitoring.
	ExUsagePccRuleIds *[]string `json:"exUsagePccRuleIds,omitempty"`
}

// AssertUsageMonitoringDataRequired checks if the required fields are not zero-ed
func AssertUsageMonitoringDataRequired(obj UsageMonitoringData) error {
	elements := map[string]interface{}{
		"umId": obj.UmId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUsageMonitoringDataConstraints checks if the values respects the defined constraints
func AssertUsageMonitoringDataConstraints(obj UsageMonitoringData) error {
	if obj.VolumeThreshold != nil && *obj.VolumeThreshold < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.VolumeThresholdUplink != nil && *obj.VolumeThresholdUplink < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.VolumeThresholdDownlink != nil && *obj.VolumeThresholdDownlink < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.NextVolThreshold != nil && *obj.NextVolThreshold < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.NextVolThresholdUplink != nil && *obj.NextVolThresholdUplink < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.NextVolThresholdDownlink != nil && *obj.NextVolThresholdDownlink < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
