/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

type TraceData struct {
	TraceRef string `json:"traceRef"`

	TraceDepth TraceDepth `json:"traceDepth"`

	NeTypeList string `json:"neTypeList"`

	EventList string `json:"eventList"`

	CollectionEntityIpv4Addr string `json:"collectionEntityIpv4Addr,omitempty"`

	CollectionEntityIpv6Addr Ipv6Addr `json:"collectionEntityIpv6Addr,omitempty"`

	InterfaceList string `json:"interfaceList,omitempty"`
}

// AssertTraceDataRequired checks if the required fields are not zero-ed
func AssertTraceDataRequired(obj TraceData) error {
	elements := map[string]interface{}{
		"traceRef":   obj.TraceRef,
		"traceDepth": obj.TraceDepth,
		"neTypeList": obj.NeTypeList,
		"eventList":  obj.EventList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTraceDepthRequired(obj.TraceDepth); err != nil {
		return err
	}
	if err := AssertIpv6AddrRequired(obj.CollectionEntityIpv6Addr); err != nil {
		return err
	}
	return nil
}

// AssertTraceDataConstraints checks if the values respects the defined constraints
func AssertTraceDataConstraints(obj TraceData) error {
	return nil
}
