/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

type PduSessionType struct {
}

// AssertPduSessionTypeRequired checks if the required fields are not zero-ed
func AssertPduSessionTypeRequired(obj PduSessionType) error {
	return nil
}

// AssertPduSessionTypeConstraints checks if the values respects the defined constraints
func AssertPduSessionTypeConstraints(obj PduSessionType) error {
	return nil
}
