/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

type RuleReport struct {

	// Contains the identifier of the affected PCC rule(s).
	PccRuleIds []string `json:"pccRuleIds"`

	RuleStatus RuleStatus `json:"ruleStatus"`

	// Indicates the version of a PCC rule.
	ContVers []int32 `json:"contVers,omitempty"`

	FailureCode FailureCode `json:"failureCode,omitempty"`

	FinUnitAct FinalUnitAction `json:"finUnitAct,omitempty"`

	// indicates the RAN or NAS release cause code information.
	RanNasRelCauses []RanNasRelCause `json:"ranNasRelCauses,omitempty"`
}

// AssertRuleReportRequired checks if the required fields are not zero-ed
func AssertRuleReportRequired(obj RuleReport) error {
	elements := map[string]interface{}{
		"pccRuleIds": obj.PccRuleIds,
		"ruleStatus": obj.RuleStatus,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertRuleStatusRequired(obj.RuleStatus); err != nil {
		return err
	}
	if err := AssertFailureCodeRequired(obj.FailureCode); err != nil {
		return err
	}
	if err := AssertFinalUnitActionRequired(obj.FinUnitAct); err != nil {
		return err
	}
	for _, el := range obj.RanNasRelCauses {
		if err := AssertRanNasRelCauseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRuleReportConstraints checks if the values respects the defined constraints
func AssertRuleReportConstraints(obj RuleReport) error {
	return nil
}
