/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

import (
	"errors"
)

type AuthorizedDefaultQos struct {
	Var5qi int32 `json:"5qi,omitempty"`

	Arp Arp `json:"arp,omitempty"`

	PriorityLevel *int32 `json:"priorityLevel,omitempty"`

	AverWindow *int32 `json:"averWindow,omitempty"`

	MaxDataBurstVol *int32 `json:"maxDataBurstVol,omitempty"`

	MaxbrUl *string `json:"maxbrUl,omitempty"`

	MaxbrDl *string `json:"maxbrDl,omitempty"`

	GbrUl *string `json:"gbrUl,omitempty"`

	GbrDl *string `json:"gbrDl,omitempty"`
}

// AssertAuthorizedDefaultQosRequired checks if the required fields are not zero-ed
func AssertAuthorizedDefaultQosRequired(obj AuthorizedDefaultQos) error {
	if err := AssertArpRequired(obj.Arp); err != nil {
		return err
	}
	return nil
}

// AssertAuthorizedDefaultQosConstraints checks if the values respects the defined constraints
func AssertAuthorizedDefaultQosConstraints(obj AuthorizedDefaultQos) error {
	if obj.Var5qi < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Var5qi > 255 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	if obj.PriorityLevel != nil && *obj.PriorityLevel < 1 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.PriorityLevel != nil && *obj.PriorityLevel > 127 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	if obj.AverWindow != nil && *obj.AverWindow < 1 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.AverWindow != nil && *obj.AverWindow > 4095 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	if obj.MaxDataBurstVol != nil && *obj.MaxDataBurstVol < 1 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.MaxDataBurstVol != nil && *obj.MaxDataBurstVol > 4095 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
