/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

type Ipv6Addr struct {
}

// AssertIpv6AddrRequired checks if the required fields are not zero-ed
func AssertIpv6AddrRequired(obj Ipv6Addr) error {
	return nil
}

// AssertIpv6AddrConstraints checks if the values respects the defined constraints
func AssertIpv6AddrConstraints(obj Ipv6Addr) error {
	return nil
}
