/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

// RedirectAddressType - Possible values are - IPV4_ADDR: Indicates that the address type is in the form of \"dotted-decimal\" IPv4 address. - IPV6_ADDR: Indicates that the address type is in the form of IPv6 address. - URL: Indicates that the address type is in the form of Uniform Resource Locator. - SIP_URI: Indicates that the address type is in the form of SIP Uniform Resource Identifier.
type RedirectAddressType struct {
}

// AssertRedirectAddressTypeRequired checks if the required fields are not zero-ed
func AssertRedirectAddressTypeRequired(obj RedirectAddressType) error {
	return nil
}

// AssertRedirectAddressTypeConstraints checks if the values respects the defined constraints
func AssertRedirectAddressTypeConstraints(obj RedirectAddressType) error {
	return nil
}
