/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

// AccNetChargingAddress - Describes the network entity within the access network performing charging
type AccNetChargingAddress struct {
	AnChargIpv4Addr string `json:"anChargIpv4Addr,omitempty"`

	AnChargIpv6Addr Ipv6Addr `json:"anChargIpv6Addr,omitempty"`
}

// AssertAccNetChargingAddressRequired checks if the required fields are not zero-ed
func AssertAccNetChargingAddressRequired(obj AccNetChargingAddress) error {
	if err := AssertIpv6AddrRequired(obj.AnChargIpv6Addr); err != nil {
		return err
	}
	return nil
}

// AssertAccNetChargingAddressConstraints checks if the values respects the defined constraints
func AssertAccNetChargingAddressConstraints(obj AccNetChargingAddress) error {
	return nil
}
