/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

type ServingNfIdentity struct {
	ServNfInstId string `json:"servNfInstId,omitempty"`

	Guami Guami `json:"guami,omitempty"`

	AnGwAddr *AnGwAddress `json:"anGwAddr,omitempty"`
}

// AssertServingNfIdentityRequired checks if the required fields are not zero-ed
func AssertServingNfIdentityRequired(obj ServingNfIdentity) error {
	if err := AssertGuamiRequired(obj.Guami); err != nil {
		return err
	}
	if obj.AnGwAddr != nil {
		if err := AssertAnGwAddressRequired(*obj.AnGwAddr); err != nil {
			return err
		}
	}
	return nil
}

// AssertServingNfIdentityConstraints checks if the values respects the defined constraints
func AssertServingNfIdentityConstraints(obj ServingNfIdentity) error {
	return nil
}
