/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_pcf_srv

import (
	"errors"
)

type AccNetChId struct {
	AccNetChaIdValue int32 `json:"accNetChaIdValue"`

	// Contains the identifier of the PCC rule(s) associated to the provided Access Network Charging Identifier.
	RefPccRuleIds []string `json:"refPccRuleIds,omitempty"`

	// When it is included and set to true, indicates the Access Network Charging Identifier applies to the whole PDU Session
	SessionChScope bool `json:"sessionChScope,omitempty"`
}

// AssertAccNetChIdRequired checks if the required fields are not zero-ed
func AssertAccNetChIdRequired(obj AccNetChId) error {
	elements := map[string]interface{}{
		"accNetChaIdValue": obj.AccNetChaIdValue,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAccNetChIdConstraints checks if the values respects the defined constraints
func AssertAccNetChIdConstraints(obj AccNetChId) error {
	if obj.AccNetChaIdValue < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
