/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 2.2.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_udr_cli

import (
	"encoding/json"
)

// checks if the SmscData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmscData{}

// SmscData Addresses of SM-Service Center entities with SMS wating to be delivered to the UE.
type SmscData struct {
	SmscMapAddress *string `json:"smscMapAddress,omitempty"`
	SmscDiameterAddress *NetworkNodeDiameterAddress1 `json:"smscDiameterAddress,omitempty"`
}

// NewSmscData instantiates a new SmscData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmscData() *SmscData {
	this := SmscData{}
	return &this
}

// NewSmscDataWithDefaults instantiates a new SmscData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmscDataWithDefaults() *SmscData {
	this := SmscData{}
	return &this
}

// GetSmscMapAddress returns the SmscMapAddress field value if set, zero value otherwise.
func (o *SmscData) GetSmscMapAddress() string {
	if o == nil || IsNil(o.SmscMapAddress) {
		var ret string
		return ret
	}
	return *o.SmscMapAddress
}

// GetSmscMapAddressOk returns a tuple with the SmscMapAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmscData) GetSmscMapAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SmscMapAddress) {
		return nil, false
	}
	return o.SmscMapAddress, true
}

// HasSmscMapAddress returns a boolean if a field has been set.
func (o *SmscData) HasSmscMapAddress() bool {
	if o != nil && !IsNil(o.SmscMapAddress) {
		return true
	}

	return false
}

// SetSmscMapAddress gets a reference to the given string and assigns it to the SmscMapAddress field.
func (o *SmscData) SetSmscMapAddress(v string) {
	o.SmscMapAddress = &v
}

// GetSmscDiameterAddress returns the SmscDiameterAddress field value if set, zero value otherwise.
func (o *SmscData) GetSmscDiameterAddress() NetworkNodeDiameterAddress1 {
	if o == nil || IsNil(o.SmscDiameterAddress) {
		var ret NetworkNodeDiameterAddress1
		return ret
	}
	return *o.SmscDiameterAddress
}

// GetSmscDiameterAddressOk returns a tuple with the SmscDiameterAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmscData) GetSmscDiameterAddressOk() (*NetworkNodeDiameterAddress1, bool) {
	if o == nil || IsNil(o.SmscDiameterAddress) {
		return nil, false
	}
	return o.SmscDiameterAddress, true
}

// HasSmscDiameterAddress returns a boolean if a field has been set.
func (o *SmscData) HasSmscDiameterAddress() bool {
	if o != nil && !IsNil(o.SmscDiameterAddress) {
		return true
	}

	return false
}

// SetSmscDiameterAddress gets a reference to the given NetworkNodeDiameterAddress1 and assigns it to the SmscDiameterAddress field.
func (o *SmscData) SetSmscDiameterAddress(v NetworkNodeDiameterAddress1) {
	o.SmscDiameterAddress = &v
}

func (o SmscData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmscData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SmscMapAddress) {
		toSerialize["smscMapAddress"] = o.SmscMapAddress
	}
	if !IsNil(o.SmscDiameterAddress) {
		toSerialize["smscDiameterAddress"] = o.SmscDiameterAddress
	}
	return toSerialize, nil
}

type NullableSmscData struct {
	value *SmscData
	isSet bool
}

func (v NullableSmscData) Get() *SmscData {
	return v.value
}

func (v *NullableSmscData) Set(val *SmscData) {
	v.value = val
	v.isSet = true
}

func (v NullableSmscData) IsSet() bool {
	return v.isSet
}

func (v *NullableSmscData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmscData(val *SmscData) *NullableSmscData {
	return &NullableSmscData{value: val, isSet: true}
}

func (v NullableSmscData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmscData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


